/* Read-only renderers shared by the blessings index and map overlays. */
'use strict';
window.SaqrimBlessingsUI=(()=>{
 const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const norm=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘]/g,"'").toLowerCase();
 const faith=()=>window.SaqrimFaithData,stones=()=>window.SaqrimStonesData;
 const worldNames={skyrim:'Skyrim',solstheim:'Solstheim',apocrypha:'Apocrypha','forgotten-vale':'Forgotten Vale','soul-cairn':'Soul Cairn',blackreach:'Blackreach',evergloam:'Evergloam',icemoth:'Icemoth',atmora:'Atmora','beyond-reach':'Beyond Reach'};
 const worldName=id=>worldNames[id]||id;
 const precisions={site:'Named-site reference · approximate area','shared-site':'Shared site · three separate stones',nearby:'Nearby landmark · NOT the shrine',town:'Town reference · NOT the exact shrine',interior:'Interior / access reference · NOT the altar',unmapped:'Directions only · no calibrated pin'};
 const race=value=>stones().races.includes(value)?value:'Breton';
 function link(href,label){const a=node('a','faith-link',label);try{const u=new URL(href,location.href);if(!['https:','http:'].includes(u.protocol))return a;a.href=u.href;if(u.origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer';}}catch(_){}return a;}
 function section(parent,title,text,cls=''){const s=node('section','faith-benefit '+cls);s.append(node('h4','',title),node('p','',text));parent.append(s);return s;}
 function sourceBox(parent,urls,note){const d=node('details','faith-sources');d.append(node('summary','','Sources & version scope'));if(note)d.append(node('p','faith-small',note));for(const [u,label]of urls)d.append(link(u,label));parent.append(d);}
 function mapURL(entry,kind,selectedRace='Breton'){const file=entry.world==='skyrim'?'map.html':'worlds.html';const u=new URL(file,location.href);if(entry.world!=='skyrim')u.searchParams.set('world',entry.world);u.searchParams.set('race',race(selectedRace));u.hash=kind+'='+entry.id;return u.pathname+u.search+u.hash;}
 function resolve(entry,mainPlaces,realmPlaces){if(!entry.mapPlace)return null;const mainland=entry.world==='skyrim';const p=(mainland?mainPlaces:realmPlaces).find(p=>p.name===entry.mapPlace&&(mainland||p.world===entry.world));if(!p)return null;if(mainland){if(Array.isArray(p.latlng)&&p.latlng.every(Number.isFinite))return{...p,position:p.latlng};if(Number.isFinite(p.x)&&Number.isFinite(p.y))return{...p,position:[p.y/8,p.x/8]};}else if(Number.isFinite(p.x)&&Number.isFinite(p.y))return{...p,position:[p.y,p.x]};return null;}
 function locationRow(s,options={}){const box=node('div','faith-location');box.dataset.shrine=s.id;box.append(node('strong','',s.name),node('p','faith-small',worldName(s.world)+' · '+(precisions[s.precision]||s.precision)),node('p','',s.directions));if(s.mapPlace)box.append(node('p','faith-small','Reference landmark: '+s.mapPlace));const positioned=options.resolve?!!options.resolve(s):null;if(positioned===false)box.append(node('p','faith-warning','No calibrated point for this entry in the current atlas. The directions remain available.'));const actions=node('div','faith-actions');if(options.onShrine){const b=node('button','','Open shrine details');b.type='button';b.addEventListener('click',()=>options.onShrine(s.id));actions.append(b);}actions.append(link(mapURL(s,'shrine',options.race),positioned===false?'Open world / location notes →':'Show shrine reference on map →'));box.append(actions);return box;}
 function deityCard(d,options={}){const card=node('details','faith-card faith-deity');card.id=options.id||'deity-'+d.id;card.dataset.deity=d.id;card.open=!!options.open;const summary=node('summary');summary.append(node('span','faith-kicker',d.pantheon),node('h3','',d.name),node('p','faith-preview',d.follower),node('span','faith-open','Blessing · Follower · 100% Devotee ↓'));card.append(summary);const body=node('div','faith-card-body');section(body,'Shrine blessing',d.blessing);section(body,'Follower benefit',d.follower);section(body,'Devotee · unlocked at 100% favor',d.devotee,'faith-devotee');body.append(node('p','faith-small','100% is the favor threshold, not an automatic +100% increase. Where a benefit scales with favor, an exact 100%-favor magnitude has not been inferred.'));section(body,'Who can follow',d.eligibility);section(body,'Worship & favor',d.worship);if(options.locations!==false){const ds=node('details','faith-locations');ds.append(node('summary','','Shrine locations / access ('+d.shrines.length+')'));for(const id of d.shrines){const s=faith().shrines.find(s=>s.id===id);ds.append(locationRow(s,options));}body.append(ds);}if(d.catalog?.length){const a=node('div','faith-actions');for(const id of d.catalog)a.append(link('./#'+id,'Related catalog entry '+id));body.append(a);}sourceBox(body,[[d.source,'Wintersun · original author'],[faith().locationsSource,'Author shrine-location readme']],'Wintersun: recorded menu v3.2.0; author reference v3.2.0. Your PS5 port and later overrides have not been play-tested. This is a summarized reference, not an exhaustive list of every favor change.');card.append(body);return card;}
 function shrineCard(s,options={}){const article=node('article','faith-shrine-detail');article.dataset.shrine=s.id;article.append(node('h2','',s.name),node('p','faith-precision',precisions[s.precision]||s.precision),node('p','',s.directions));if(s.mapPlace)article.append(node('p','faith-small','Map reference: '+s.mapPlace+' · '+worldName(s.world)));if(options.resolve&&!options.resolve(s))article.append(node('p','faith-warning','This entry has no calibrated pin in the current map. No position has been invented.'));for(const id of s.deities){const deity=faith().deities.find(d=>d.id===id);article.append(deityCard(deity,{...options,id:'shrine-profile-'+s.id+'-'+id,open:s.deities.length===1,locations:false}));}article.append(link('blessings.html#shrine='+s.id,'Open in Shrines & stones →'));sourceBox(article,[[s.source,'Location source']],'Named-site pins are approximate area references. Nearby, town and interior references are not exact altar positions.');return article;}
 function stoneEffects(parent,stone,r){const effect=stones().effects[r][stone.key];section(parent,r+' · '+effect.name,effect.text);if(effect.extra)section(parent,'Breton extra · Stones of Galen · '+effect.extra.name,effect.extra.text,'faith-breton-extra');return effect;}
 function stoneCard(stone,selectedRace,options={}){const r=race(selectedRace),effect=stones().effects[r][stone.key];const card=node('details','faith-card faith-stone');card.id=options.id||'stone-'+stone.id;card.dataset.stone=stone.id;card.dataset.race=r;card.open=!!options.open;const summary=node('summary');summary.append(node('span','faith-kicker','Freyr · '+r+(effect.extra?' · 2 effects':'')),node('h3','',stone.name),node('p','faith-preview',effect.name+': '+effect.text));if(effect.extra)summary.append(node('p','faith-extra-preview','+ '+effect.extra.name+': '+effect.extra.text));summary.append(node('span','faith-open','Effects, location & race comparison ↓'));card.append(summary);const body=node('div','faith-card-body');stoneEffects(body,stone,r);body.append(node('p','faith-warning','Freyr replaces the normal stone effect. Do not add vanilla, Andromeda or Imperious bonuses. This is a race preview, not a reading of your console character.'));section(body,'Location',stone.directions);body.append(node('p','faith-small',precisions[stone.precision]+' · '+stone.mapPlace));const positioned=options.resolve?!!options.resolve(stone):null;if(positioned===false)body.append(node('p','faith-warning','The named stone is not positioned in the current atlas; location notes are still available.'));const actions=node('div','faith-actions');if(options.onStone){const b=node('button','','Select this stone');b.type='button';b.addEventListener('click',()=>options.onStone(stone.id));actions.append(b);}actions.append(link(mapURL(stone,'stone',r),'Show stone reference on map →'),link('blessings.html?tab=stones&race='+encodeURIComponent(r)+'#stone='+stone.id,'Link to this race / stone'));body.append(actions);const raceDetails=node('details','faith-race-context');raceDetails.append(node('summary','','Mannaz racial context & caveats'),node('p','',stones().raceNotes[r]));if(stones().raceCaveats[r])raceDetails.append(node('p','faith-warning',stones().raceCaveats[r]));body.append(raceDetails);const compare=node('details','faith-comparison');compare.append(node('summary','','Compare all 10 races at this stone'));for(const other of stones().races){const row=node('section','faith-compare-row');stoneEffects(row,stone,other);compare.append(row);}body.append(compare);sourceBox(body,[[stones().source,'Freyr · original author'],[stones().raceSource,'Mannaz · original author'],['load-order.html#mod-028','Recorded Mannaz entry #28'],['load-order.html#mod-029','Recorded Freyr entry #29']],'Author-reference Freyr 1.2.0 and Mannaz 3.0.1. Both recorded PS5 menu versions say v1.00, which does not establish the underlying PC version. Exact PS5 parity remains unverified.');card.append(body);return card;}
 function raceSelect(id,initial,onChange){const label=node('label','faith-select-label','Preview race'),select=node('select');select.id=id;for(const r of stones().races){const o=node('option','',r);o.value=r;select.append(o);}select.value=race(initial);label.append(select);select.addEventListener('change',()=>onChange(select.value));return{label,select};}
 return{node,norm,link,section,worldName,precisions,race,mapURL,resolve,locationRow,deityCard,shrineCard,stoneCard,raceSelect};
})();
