/* Reference facts summarized from Enai Siaion's Wintersun 3.2.0 documentation.
   Original catalog unchanged; map references are not surveyed altar coordinates. */
'use strict';
window.SaqrimFaithData=(()=>{
 const source='https://www.nexusmods.com/skyrimspecialedition/mods/22506',locationsSource=source+'?tab=docs';
 const slug=s=>s.toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 // name | pantheon | eligibility | blessing | follower | devotee | worship
 const rows=`Akatosh|Divines|Everyone|Skill experience +10%.|Father of Dragons: increased effectiveness against dragons for attacks, magic, shouts and enchantments; scales with favor.|Turn the Hourglass: prayer resets the most recently used shout and power cooldowns.|Advance the main story, gain levels and dragon souls; avoid bounties.
Arkay|Divines|Everyone|Health +25.|Chalice of Life: missing Health increases regeneration, up to 5% of maximum Health per second; enables Arkay's Rites.|Arkayn Cycle: fatal damage instead restores full Health, spending 15% favor. Pray before it can trigger again.|Destroy undead and their summoners; perform Rites. Do not raise undead or become undead; avoid bounties.
Dibella|Divines|Everyone|Prices improve by 10%.|Afterglow: Lover's Comfort also gives +5% to all skills.|Dibellan Arts: activate a person during combat to strip their equipment and make them follow for 90 seconds; 5% favor.|Persuasion, Lover's Comfort and finding the Sybil; pray without clothing and avoid bounties.
Julianos|Divines|Everyone|Magicka +25.|Divine Student: reduced spell costs, scaling with favor.|Temple of Logic: increased spell and scroll effectiveness, scaling with favor.|Develop Mage skills and Magicka; avoid bounties. No fixed percentage at 100 favor is inferred here.
Kynareth|Divines|Everyone|Stamina +25.|Windspeaker: movement speed +10% during combat.|Kynareth's Emissary: prayer summons a sacred sabre-cat mount.|Explore, increase Stamina and obtain Voice of the Sky. Pray outdoors; the Temple of Kynareth is an author-documented exception. Avoid bounties.
Mara|Divines|Everyone|Restoration cost -10%.|Cleansing: prayer removes diseases from you and allies within 40 feet.|Aura of Peace: heals living allies in a 40-foot radius; healing scales with favor.|Marriage, home ownership, generosity and Lover's Comfort; avoid bounties.
Stendarr|Divines|Everyone|Blocking effectiveness +10%.|Sacred Resolve: reduced attack damage from undead and Daedra; scales with favor.|Channel Divinity: spend 10% favor during prayer for favor-scaled attack, defense and healing bonuses, lasting 5 minutes or 3 battles.|Clear dungeons, kill undead/Daedra and complete side quests; avoid crime and all summoning arts.
Talos|Divines|Everyone|Shout cooldown -20%.|Stormlord: attacks, criticals and shouts gain effectiveness against elves; scales with favor.|Dragon of the North: an enemy death within 40 feet halves the remaining shout cooldown.|Civil War progress, Words, dragon souls and defeating elves/Thalmor; avoid bounties.
Zenithar|Divines|Everyone|Smithing improvements +10%.|Work Ethic: Smithing, Alchemy and Enchanting become better and improve faster; scales with favor.|Invisible Hand: buy and sell through prayer.|Invest in merchants, train skills and craft equipment; avoid bounties.
Azura|Daedric princes|Dark Elf or Khajiit; otherwise complete The Black Star|Magic resistance +10%.|Twilight Shroud: foes within 40 feet lose magic resistance (favor-scaled) and cannot absorb spells.|Perfume of Moonshadow: activate a sufficiently weakened person in combat to paralyze them at 1 Health; 5% favor. Health threshold scales with favor.|Soul trapping and exploration; pray at twilight, preferably outside. Dark Elves and Illusion skill improve favor gains.
Boethiah|Daedric princes|Dark Elf; otherwise complete Boethiah's Calling|One-handed effectiveness +10%.|Blood Throne: increased attack damage when facing a single opponent; scales with favor.|Assassinate: prayer can grant 90-second Daedric invisibility; breaking it with a sneak attack adds 50% damage. Costs 10% favor.|Murder, sneak attacks and poisoning are named in the tenets; Dark Elves favored. The 3.0 changelog changes the old poisoning favor source to killing people.
Clavicus Vile|Daedric princes|Dark Elf; otherwise complete A Daedra's Best Friend|Conjuration cost -10%.|Pactmaker: Conjuration duration +10%; prayer offers timed Pacts for favor.|Wishmaster: exchange 30% favor during prayer for one permanent perk point.|Complete Pacts exactly and on time; ordinary prayer does not itself build favor for this deity.
Hermaeus Mora|Daedric princes|Wood Elf; or complete Discerning the Transmundane / At the Summit of Apocrypha|Self-targeted spells/effects last 15% longer.|Demon of Knowledge: corpse-looted Eldritch Pages can be bound at a tanning rack into magic/shout-enhancing tomes.|Omniscience: prayer spends 5% favor for one permanent level in a chosen skill.|Read pages, tomes and skill books; complete the Apocrypha story. Tome benefits depend on continuing worship.
Hircine|Daedric princes|Breton, Wood Elf or werewolf; otherwise complete Ill Met by Moonlight|Restore 2% maximum Stamina per second.|Bitter Mercy: double attack damage against living targets below a favor-dependent Health threshold.|Posting of the Hunt: spend 10% favor while praying to reveal living targets within 500 feet and expose them to Bitter Mercy.|Fight living opponents openly, especially stronger foes; werewolf lifestyle and wilderness prayer. Light Armor skill helps favor.
Jyggalag|Daedric princes|Everyone|Attack and critical damage against Daedra +15%.|Obelisks of Order: eight world obelisks; each activation grants +15 Health, Magicka and Stamina.|Stasis: activate an opponent in combat to immobilize them while making them invulnerable for 15 seconds; 5% favor.|Activate obelisks, clear dungeons and kill Daedra; do not serve Sheogorath. Heavy Armor skill helps favor.
Malacath|Daedric princes|Dark Elf or Orc; otherwise complete The Cursed Tribe|Power-attack Stamina cost -15%.|Deathbringer: power-attack damage rises with favor.|Bloodsoaked Triumph: a death within 40 feet heals the killer using a favor-scaled fraction of overkill damage.|Defeat mighty foes and improve gear; no crimes against strongholds. Orcs and Smithing skill favored.
Mehrunes Dagon|Daedric princes|Dark Elf or Khajiit; otherwise complete Pieces of the Past|Destruction effectiveness +10%.|Self-Immolation: prayer drains Magicka; stopping at 20% or lower yields extra favor and Burning Path charges.|Burning Path: nearby foes take fire damage and explode on death; damage scales with favor. Prayer recharges it.|Kill people and desecrate enemy shrines; Destruction skill helps favor.
Mephala|Daedric princes|Dark Elf or Khajiit; otherwise complete The Whispering Door|Crafted poisons +15% effectiveness.|Secret Murder: sneak attacks from behind gain favor-scaled damage.|Whispers of Betrayal: prayer controls the closest person within 75 feet to fight for you; 5% favor.|Poison weapons, sneak attack and intimidate; Dark Elves favored.
Meridia|Daedric princes|High Elf; otherwise complete The Break of Dawn|Restoration effectiveness +10%.|Purification: increased effectiveness against undead for attacks, spells, shouts and enchantments; scales with favor.|Supreme Light: activate an undead enemy for a favor-scaled solar strike, with half damage to nearby undead; 10% favor.|Destroy undead; never summon them or become one. High Elves and Restoration skill favored.
Molag Bal|Daedric princes|Dark Elf or vampire; otherwise complete The House of Horrors|Destruction cost -10%.|Eye of the Storm: drains nearby enemies' Magicka and Stamina in combat; amount scales with favor.|Dragged to Oblivion: banish a person in combat to Coldharbour for 15% favor, then pray to recover their items.|Kill people and trap souls; embrace vampirism rather than curing it. Destruction skill helps favor.
Namira|Daedric princes|Dark Elf; otherwise complete The Taste of Death|Poison resistance +50%.|Creeping Decay: reduces Poison Resist in a 40-foot radius; scales with favor.|Necrophages: poisoning a person or placing Human Heart/Flesh on them causes insects, armor loss and disease damage; scales with favor.|Murder, weapon poisoning, cannibalism with Namira's Ring and gifts to beggars.
Nocturnal|Daedric princes|Dark Elf; otherwise complete Darkness Returns|Detection difficulty +10% while sneaking.|Vanish in the Night: prayer clears nonviolent bounties up to a favor-dependent gold limit.|Raven's Watch: prayer enables astral observation of the nearest person within 300 feet.|Pick locks and Mysterious Coinpurses; pray at night in darkness. Sneak skill helps favor.
Peryite|Daedric princes|While diseased; otherwise complete The Only Cure|Disease resistance +25%; followers are not cured by this shrine.|Taskmaster: faster skill learning, scaling with favor; accept Gifts during prayer.|Green Dragon's Breath: transmit your Gifts to a living opponent, adding 5 disease damage/second per Gift. Prayer recharges it.|Maintain diseases and accept Gifts; pray only while diseased. Curing afflictions can cause abandonment.
Sanguine|Daedric princes|Dark Elf; otherwise complete A Night to Remember|Consumed beneficial potions/ingredients +15% effectiveness.|Be Merry: Health, Magicka and Stamina regeneration +50% while a potion, food or ingredient effect is active.|Pandemonium: combat prayer makes the five closest hostile people dance for 20 seconds; 10% favor.|Drink alcohol, cause mischief/crime and escape jail.
Sheogorath|Daedric princes|Dark Elf or Khajiit; otherwise complete The Mind of Madness|A randomly chosen blessing.|Touch of Madness: prayer gives a random effect; higher favor improves the odds of beneficial results.|Lost to Madness: entering combat also triggers a Touch of Madness.|Pray regularly; respect cheese. Results are intentionally unpredictable.
Vaermina|Daedric princes|Dark Elf; otherwise complete Waking Nightmare|Illusion cost -10%.|Night Terrors: raises the target-level limit of mind-affecting Illusion spells; scales with favor.|Phantasmagoria: activate a sleeping person for a one-hour illusory companion; 10% favor.|Sleep to pray, kill sleepers, witness deaths under your mind effects; Illusion skill helps favor.
Auriel|Elven ancestors|Breton, High Elf or Wood Elf|Missile-weapon effectiveness +10%.|Father of Mer: faster skill learning, scaling with favor.|Path to Alaxon: skills reaching level 100 gain favor-scaled effectiveness.|Main story, skill mastery and Chantry champion; High Elves favored.
Jephre|Elven ancestors|Everyone|Carry capacity +25.|Forest Stride: movement speed +10% outside combat.|The Eternal Song: very fast out-of-combat Stamina regeneration; prayer clears the weather.|Explore, read stories and hunt; Wood Elves favored.
Magnus|Elven ancestors|Everyone|Hostile-spell absorption chance +10%.|Sight, Light and Insight: spells cost 75% less, but normal Magicka regeneration stops; prayer replenishes it.|Architect's Gift: prayer casts beneficial self spells held in your hands for free, with favor-scaled extra duration.|Use magic successfully during prayer, protect the Eye of Magnus and enchant items.
Phynaster|Elven ancestors|Breton, High Elf or Wood Elf|Alchemy strength +10% for potions and poisons.|Shorter Strides: all three attributes regenerate 100% faster while stationary, but 50% slower while moving.|Elvenpath: prayer can return you to your previous prayer location; 2% favor.|Explore, find standing stones and harvest; Bretons favored.
Syrabane|Elven ancestors|Breton, High Elf or Wood Elf|Restore 2% maximum Magicka per second.|Knowledge Seeker: defeated enemies are more likely to carry scrolls and spell tomes.|Reach for the Stars: faster Mage-skill experience, scaling with favor.|Read skill books and learn varied spells; High Elves favored.
Trinimac|Elven ancestors|High Elf, Orc or Wood Elf|Two-handed effectiveness +10%.|Tears of Man: attack and critical damage against humans rises with favor.|Manifest Divinity: prayer can make you ethereal and invulnerable until your next attack; 5% favor.|Defeat humans and mighty foes; never serve Boethiah or take her blessing. Two-Handed skill helps favor.
Xarxes|Elven ancestors|Breton, High Elf or Wood Elf|Scroll effectiveness +25%.|Scribe's Insight: reading a skill book while praying gives one extra level in that skill.|Panopticon: prayer provides an elevated trance revealing characters over a large radius.|Explore, read stories and learn diverse spells; Bretons favored.
Z'en|Elven ancestors|Wood Elf|Alteration cost -10%.|Traveler's Break: beneficial consumables used while praying last twice as long and gain favor-scaled strength.|Merchant's Knapsack: prayer opens unlimited extradimensional storage.|Bribe when needed, harvest and eat food; Speech skill improves favor gains.
Leki|Yokudan pantheon|Redguard|Light-armor rating +10%.|Spirit Sword: power attacks ignore a favor-scaled portion of enemy armor.|Battle Meditation: spend 5% favor while praying for favor-scaled melee damage, lasting 10 minutes or 5 battles.|Advance the Civil War, craft/improve weapons and develop Warrior skills.
Morwha|Yokudan pantheon|Redguard|Healing spells restore 15% more Health.|Healer of the Sands: prayer heals you and nearby allies; scales with favor.|Fertile Growth: prayer supplies enchanted fruit that restores or fortifies an attribute.|Marriage, Lover's Comfort, harvesting and eating food.
Satakal|Yokudan pantheon|Redguard|Restore 2% maximum Health per second.|World Egg: other gods' shrine blessings become stronger and longer; scales with favor.|Ouroboros: redistribute attribute points through prayer for 15% favor.|Main-story progress, Health and dragon souls.
Tall Papa|Yokudan pantheon|Redguard|Enchantment strength +10%.|Metaphysical Insight: weapon enchantments use less charge; scales with favor.|Glimpse the Shores: lethal damage grants an ethereal grace period; ending combat in time revives you for 10% favor. Duration scales with favor; pray to reset.|Find Fractures and enchant items; Enchanting skill helps favor.
The HoonDing|Yokudan pantheon|Redguard|Attack/bash stagger effectiveness +50%.|Make Way: staggering an opponent reduces their armor for 5 seconds; scales with favor.|Perseverance: favor-scaled resistance to stagger from attacks and bashes.|Win open fights, especially against stronger enemies; One-Handed skill helps favor.
Rajhin|Khajiiti pantheon|Khajiit|Lockpicking ease +10%.|Rajhin's Tales: containers can hold extra gold, with occasional larger finds.|Prayer of Unlocking: spend 5% favor to open a pickable lock within 20 feet; does not bypass key-only locks.|Explore, bribe and pick locks; Lockpicking skill helps favor.
Riddle'Thar|Khajiiti pantheon|Khajiit|Unarmed damage +10.|Path to Llesw'er: all skills gain favor-scaled effectiveness.|Beseech the Manes: prayer grants a context-sensitive blessing selected by an ancient Mane.|Balance Warrior/Thief/Mage skills and all three attributes; pray at night.
Baan Dar|Other deities|Khajiit or Wood Elf|Pickpocketing ease +10%.|Pariah: easier pickpocketing but worse purchase prices with other races; scales with favor.|Skooma Trick: planted skooma bottles can be ignited through prayer within 200 feet; damage scales with favor, cost 5% favor.|Pick locks and pockets; Khajiit and Archery skill favored.
Ebonarm|Other deities|Everyone|Heavy-armor rating +10%.|Enemy of the Daedra: attack/critical effectiveness against Daedra and their summoners rises with favor.|Raven's Harvest: take armor from enemies within 40 feet and add the total to your own; doubled against Daedra, scales with favor.|Defeat Daedra and mighty foes, complete miscellaneous quests; Block skill helps favor.
Mannimarco|Other deities|Everyone|Conjuration effectiveness +10%.|Dark Moon: undead summoned at night last longer; scales with favor.|Nocturne: allied conjured undead gain favor-scaled attack damage and Health regeneration.|Trap souls, pray at night and reject Arkay's blessing; Conjuration skill helps favor.
Shor|Other deities|Breton, Imperial, Nord or Redguard|Attack and critical damage against elves +15%.|Another Name for Freedom: less attack damage and stagger from elves; scales with favor.|Destiny: a Shield-Thane joins battles against powerful foes; prayer recharges it.|Advance the main story, master Warrior skills, defeat elves and mighty foes.
Sithis|Other deities|Argonian; otherwise complete Innocence Lost|Sneak-attack damage +15%.|Primal Darkness: up to 25% harder to detect by people within 30 feet; killed people may carry Human Hearts.|Call of the Void: while sneaking, turn a door into a brief portal that kills nearby undetecting targets within 60 feet; 5% favor.|Murder, sacrifice Human Heart/Flesh while praying, use the Void; Argonians favored.
St. Alessia|Other deities|Breton, Imperial, Nord or Redguard|Followers within 20 feet gain +50 armor and +10% magic resistance.|Covenant of Man: choose a Divine blessing through prayer; its strength scales with favor.|Dragonblood Empress: while Divinely blessed, befriend most nonhostile humans as potential followers; 10% favor.|Keep a follower, defeat elves and receive a Divine blessing.
The All-Maker|Other deities|Breton, Imperial, Nord or Redguard|Attack and critical damage against animals +15%.|Wellspring of Life: healing spells restore more Health, scaling with favor.|World Shaman: after using an All-Maker Stone power, prayer restores it.|Cleanse the All-Maker Stones, hunt, explore and pray outdoors; Nords favored.
The Hist|Other deities|Argonian|Armor +50.|Symbiosis: prayer temporarily boosts all three attributes; amount and duration scale with favor.|Deep Roots: drain a favor-scaled share of Magicka and Stamina from nearby dead creatures/people within 60 feet.|Explore, defeat Daedra and pray outdoors; never summon Daedra.
The Magna-Ge|Other deities|Everyone|Alteration effectiveness +10%.|Shimmering Light: restore 5 weapon-charge points/second, capped at the charge when last equipped/recharged.|Starlit Path: prayer teleports you to a visible location; 4% favor.|Enchant and explore; pray outdoors at night. High Elves and Alteration skill favored.
The Old Ways|Other deities|Breton or Nord|Attack and critical damage against animals +15%.|Totem Worship: sacrifice gemstones worth 100 gold during prayer to receive an animal-god power.|Dragon Cult: unlocks the Dragon option; costs 2% favor per hour. Detailed Dragon-effect numbers are not specified in this profile.|Defeat people, absorb dragon souls and invoke animal powers; Nords favored.`;
 const deities=rows.split('\n').map(row=>{const [name,pantheon,eligibility,blessing,follower,devotee,worship]=row.split('|');return{id:slug(name),name,pantheon,eligibility,blessing,follower,devotee,worship,source,devoteeFavor:100};});
 const shrines=[];
 function shrine(id,name,gods,world,place,precision,directions,ref=locationsSource){shrines.push({id,name,deities:gods.split('|').map(slug),world,mapPlace:place,precision,directions,source:ref});}
 shrine('divines-solitude','Temple of the Divines','Akatosh|Arkay|Dibella|Julianos|Kynareth|Mara|Stendarr|Zenithar','skyrim','Solitude','interior','Inside the Temple of the Divines. Solitude is the town reference, not eight separate outdoor shrines. Talos availability here is conditional, so use the separate Talos references.','https://en.uesp.net/wiki/Skyrim:Temple_of_the_Divines');
 shrine('talos-whiterun','Talos · Whiterun','Talos','skyrim','Whiterun','town','Talos shrine near the Gildergreen; map pin uses Whiterun, not the exact statue.','https://en.uesp.net/wiki/Skyrim:Whiterun');
 shrine('kynareth-whiterun','Temple of Kynareth','Kynareth','skyrim','Whiterun','interior','Inside the Temple of Kynareth; town reference only.','https://en.uesp.net/wiki/Skyrim:Temple_of_Kynareth');
 shrine('mara-riften','Temple of Mara','Mara','skyrim','Riften','interior','Inside the Temple of Mara; town reference only.','https://en.uesp.net/wiki/Skyrim:Temple_of_Mara');
 shrine('dibella-markarth','Temple of Dibella','Dibella','skyrim','Markarth','interior','Inside the Temple of Dibella; town reference only.','https://en.uesp.net/wiki/Skyrim:Temple_of_Dibella');
 shrine('stendarr-beacon',"Stendarr's Beacon",'Stendarr','skyrim',"Stendarr's Beacon",'site','Shrine at the beacon; existing exterior reference.','https://en.uesp.net/wiki/Skyrim:Stendarr%27s_Beacon');
 shrine('azura','Shrine of Azura','Azura','skyrim','Shrine of Azura','site','Use the shrine at the named exterior site.');
 shrine('boethiah','Sacellum of Boethiah','Boethiah','skyrim','Sacellum of Boethiah','site','Use the shrine at the Sacellum.');
 shrine('reclamations','Raven Rock Temple','Azura|Boethiah|Mephala','solstheim','Raven Rock','interior','Inside Raven Rock Temple. The marker is the town reference, not three exact shrine positions.');
 shrine('clavicus',"Clavicus Vile · Haemar's Shame",'Clavicus Vile','skyrim',"Haemar's Shame",'interior','Shrine inside the dungeon; follow the interior route.');
 shrine('mora-coast','Hermaeus Mora · Sea of Ghosts','Hermaeus Mora','skyrim',"Septimus Signus's Outpost",'nearby',"Search the Sea of Ghosts WEST of Septimus Signus's Outpost (the author readme calls it Septimus Severus). Marker is the outpost, NOT the shrine. Added in Wintersun 3.1.0.");
 shrine('mora-apocrypha','Hermaeus Mora · Waking Dreams','Hermaeus Mora','apocrypha',null,'unmapped','Waking Dreams / Apocrypha. The readme mentions Chapter I and the changelog also mentions the end near the respec gates; exact spatial mapping remains pending.');
 shrine('hircine-glenmoril','Hircine · Glenmoril Coven','Hircine','skyrim','Glenmoril Coven','interior','Use the shrine inside Glenmoril Coven.');
 shrine('hircine-snowclad','Hircine · Snowclad Ruins','Hircine','solstheim','Snowclad Ruins','site','Shrine at Snowclad Ruins; displayed only if the current realm atlas contains this place.');
 shrine('hircine-gjukar','Hircine · north of Gjukar','Hircine','skyrim',"Gjukar's Monument",'nearby',"Search NORTH of Gjukar's Monument; marker is the landmark, not the shrine.");
 shrine('jyggalag','Jyggalag · west of Dawnstar','Jyggalag','skyrim','Dawnstar','nearby','Search wilderness WEST of Dawnstar; exact shrine coordinates not established.');
 shrine('malacath','Malacath · Fallowstone route','Malacath','skyrim','Fallowstone Cave','interior',"Follow Fallowstone Cave toward Malacath's shrine; the cave entrance is an access reference, not the interior altar.");
 shrine('dagon','Shrine of Mehrunes Dagon','Mehrunes Dagon','skyrim','Shrine of Mehrunes Dagon','site','Named shrine site; access conditions still apply.');
 shrine('meridia','Statue to Meridia','Meridia','skyrim','Statue to Meridia','site','Shrine at the statue; not a pin for Dawnbreaker.');
 shrine('molag','Molag Bal · Volkihar Keep','Molag Bal','skyrim','Castle Volkihar','interior','Wintersun readme names Volkihar Keep; marker is the castle exterior. The House of Horrors is also a temptation route, not silently counted as another calibrated shrine.');
 shrine('namira','Namira · Reachcliff Cave','Namira','skyrim','Reachcliff Cave','interior','Shrine inside Reachcliff Cave; entrance reference only.');
 shrine('nocturnal','Nocturnal · Thieves Guild','Nocturnal','skyrim','Riften','interior','Thieves Guild headquarters beneath Riften; town marker, not exact shrine coordinates.');
 shrine('peryite','Shrine to Peryite','Peryite','skyrim','Shrine to Peryite','site','Named shrine site. Followers should preserve their diseases.');
 shrine('sanguine','Sanguine · south of Kynesgrove','Sanguine','skyrim','Kynesgrove','nearby','Search wilderness SOUTH of Kynesgrove; village reference only.');
 shrine('sheogorath-coast',"Sheogorath · Widow's Watch",'Sheogorath','skyrim',"Widow's Watch Ruins",'nearby',"Search NORTH of Widow's Watch Ruins; marker is the ruin, not the shrine.");
 shrine('sheogorath-palace','Sheogorath · Pelagius Wing','Sheogorath','skyrim','Solitude','interior','Blue Palace, Pelagius Wing. Interior access is required; Solitude is the reference.');
 shrine('vaermina','Vaermina · Nightcaller Temple','Vaermina','skyrim','Nightcaller Temple','interior','Shrine inside Nightcaller Temple; exterior reference only.');
 shrine('ancestors','Temple of the Ancestors','Auriel|Jephre|Magnus|Phynaster|Syrabane|Trinimac|Xarxes','skyrim','Morvunskar','nearby','The author places the shared temple SOUTH of Morvunskar. This marker is Morvunskar, NOT the temple or its seven shrines.');
 shrine('auriel-darkfall','Auriel · Darkfall Cave','Auriel','skyrim','Darkfall Cave','interior','Inside Darkfall Cave, on the Dawnguard route.');
 shrine('auriel-sanctum','Auriel · Inner Sanctum','Auriel','forgotten-vale',null,'unmapped','Inner Sanctum of the Chantry; no calibrated interior coordinates in the current map.');
 shrine('auriel-solstheim','Auriel · White Ridge reference','Auriel','solstheim','White Ridge Barrow','nearby','Search wilderness NORTHEAST of White Ridge Barrow; marker is the barrow.');
 shrine('jephre','Jephre · Fort Greymoor reference','Jephre','skyrim','Fort Greymoor','nearby','Search wilderness SOUTH of Fort Greymoor; fort reference only.');
 shrine('magnus','Magnus · Bards Leap reference','Magnus','skyrim',"Bard's Leap Summit",'nearby',"Search wilderness NORTH of Bard's Leap Summit; landmark reference only.");
 shrine('phynaster','Phynaster · Nilheim reference','Phynaster','skyrim','Nilheim','nearby','Search wilderness EAST of Nilheim; landmark reference only.');
 shrine('syrabane','Syrabane · Dawnstar reference','Syrabane','skyrim','Dawnstar','nearby','Search wilderness SOUTHEAST of Dawnstar; exact shrine position not mapped.');
 shrine('trinimac','Trinimac · Mistwatch reference','Trinimac','skyrim','Mistwatch','nearby','Search wilderness NORTHEAST of Mistwatch; landmark reference only.');
 shrine('xarxes',"Xarxes · Treva's Watch reference",'Xarxes','skyrim',"Treva's Watch",'nearby',"Search wilderness SOUTH of Treva's Watch; landmark reference only.");
 shrine('zen',"Z'en · Dragon Bridge reference","Z'en",'skyrim','Dragon Bridge','nearby','Search wilderness EAST of Dragon Bridge; settlement reference only.');
 shrine('yokudan','Hillcrown Yokudan Shrine','Leki|Morwha|Satakal|Tall Papa|The HoonDing','skyrim','Rorikstead','nearby','Shared Yokudan shrine SOUTHWEST of Rorikstead; marker is Rorikstead, not the actual shrine cluster.');
 shrine('rajhin','Rajhin · Valtheim reference','Rajhin','skyrim','Valtheim Towers','nearby','Search wilderness SOUTH of Valtheim Towers.');
 shrine('riddlethar',"Riddle'Thar · Saarthal reference","Riddle'Thar",'skyrim','Saarthal','nearby','Search wilderness SOUTH of Saarthal.');
 shrine('baandar','Baan Dar · Apprentice reference','Baan Dar','skyrim','The Apprentice Stone','nearby','Search wilderness NORTHEAST of the Apprentice Stone.');
 shrine('ebonarm','Ebonarm · Reach camp reference','Ebonarm','skyrim','Reach Stormcloak Camp','nearby','Search wilderness NORTH of Reach Stormcloak Camp.');
 shrine('mannimarco','Mannimarco · Witchmist reference','Mannimarco','skyrim','Witchmist Grove','nearby','Search wilderness SOUTHWEST of Witchmist Grove.');
 shrine('shor','Shor · Snow Veil reference','Shor','skyrim','Snow Veil Sanctum','nearby','Search wilderness EAST of Snow Veil Sanctum.');
 shrine('sithis-falkreath','Sithis · Falkreath Sanctuary','Sithis','skyrim','Dark Brotherhood Sanctuary','interior','Inside the Falkreath Dark Brotherhood Sanctuary; added in Wintersun 1.3.0.');
 shrine('sithis-dawnstar','Sithis · Dawnstar Sanctuary','Sithis','skyrim','Dawnstar Sanctuary','interior','Inside the Dawnstar Dark Brotherhood Sanctuary.');
 shrine('alessia','St. Alessia · Eastmarch camp reference','St. Alessia','skyrim','Eastmarch Imperial Camp','nearby','Search wilderness SOUTHEAST of Eastmarch Imperial Camp.');
 shrine('allmaker','All-Maker · cleansed stones','The All-Maker','solstheim',null,'unmapped','Worship at cleansed All-Maker Stones. These are not the thirteen Freyr standing stones; cleansing and DLC progression matter. Individual All-Maker power/Roots locations are not calibrated here.');
 shrine('hist','The Hist · Sleeping Tree','The Hist','skyrim','Sleeping Tree Camp','site','The Sleeping Tree is the author-documented worship location.');
 shrine('magnage','Magna-Ge · Bleak Falls reference','The Magna-Ge','skyrim','Bleak Falls Barrow','nearby','Search wilderness NORTHEAST of Bleak Falls Barrow.');
 shrine('oldways','Old Ways · Bromjunaar Sanctuary','The Old Ways','skyrim','Labyrinthian','interior','Bromjunaar Sanctuary IN THE PAST, accessed through the Wooden Mask at Labyrinthian. This is not a shrine at the outside map marker.');
 const linkedCatalog={vaermina:['W417'],'hermaeus-mora':['W426'],mephala:['W425'],'clavicus-vile':['W424']};
 for(const d of deities){d.shrines=shrines.filter(s=>s.deities.includes(d.id)).map(s=>s.id);d.catalog=linkedCatalog[d.id]||[];}
 return{version:1,checked:'2026-09-18',source,locationsSource,deities,shrines,slug,notes:['Wintersun recorded menu v3.2.0; author reference v3.2.0. Installed PS5 behavior and later overrides remain untested.','100% is the favor threshold for the Devotee ability, not a universal 100% stat increase. Favor-scaled magnitudes are left qualitative where the author uses X.','Worship one deity at a time. Prayer once per game day is sufficient; rapid repeats do not accelerate normal favor gain. At zero favor the deity abandons you.','Shrine blessings, becoming a follower and reaching Devotee status are separate. Race/quest eligibility applies to following; an eligible race is not automatically your starting religion.','Shrine coverage is a documented reference list, not every duplicate vanilla altar. Nearby and town markers are explicitly not exact shrine positions.','The author description contains 51 named profiles despite its headline saying 50; this index follows the named profiles.']};
})();
