/* Quest journal. Original catalog is read-only; only saqrimQuestProgress_v1 is written. */
'use strict';
(async()=>{
 const $=id=>document.getElementById(id),KEY='saqrimQuestProgress_v1',PICK='skyrimLootChoices_v202_20260917';
 const statuses=['Not started','In progress','Completed'];
 const labels={completion:'Completion reward',choice:'Conditional / choice reward',unlock:'Completion unlock',boss:'Boss / NPC loot',optional:'Optional / route discovery',lead:'Unverified lead'};
 const realms={skyrim:'Skyrim',solstheim:'Solstheim',icemoth:'Icemoth / Hjorkvild',evergloam:'Evergloam',atmora:'Atmora / Crucible','beyond-reach':'Beyond Reach','soul-cairn':'Soul Cairn','forgotten-vale':'Forgotten Vale',apocrypha:'Apocrypha',blackreach:'Blackreach',elsweyr:'Elsweyr',variable:'Travel-dependent / variable'};
 const node=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined)n.textContent=x;return n;};
 const norm=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’‘]/g,"'");
 let quests=[],catalog=new Map(),progress={},picks={},filtered=[],storageOK=true,groups=[];
 const selected={},checks=[],cards=new Map(),itemGroups=new Set(['category','school','hand','weapon','armor','slot','origin','review']);
 function state(id){return progress[id]||{status:'Not started',rewardCollected:false,notes:''};}
 function message(t){$('quest-message').textContent=t;$('quest-message').hidden=false;}
 function read(key){try{const v=JSON.parse(localStorage.getItem(key)||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}catch(_){storageOK=false;return {};}}
 function saveNote(){$('quest-save-status').textContent=storageOK?'Quest progress and notes save in this browser only. Loot picks, ratings and the console checklist are untouched.':'Browser storage could not be read or saved. Keep a quest backup before leaving; changes may be session-only.';}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(progress));storageOK=true;}catch(_){storageOK=false;}saveNote();}
 function addLink(parent,href,text){try{const u=new URL(href,location.href);if(!['https:','http:'].includes(u.protocol))return;const a=node('a','',text);a.href=href;if(u.origin!==location.origin){a.target='_blank';a.rel='noopener noreferrer';}parent.append(a);}catch(_){}}
 function mapURL(p){if(!p||['elsweyr','variable'].includes(p.world))return null;if(p.world==='skyrim')return p.mapPlace?'map.html#place='+encodeURIComponent(p.mapPlace):null;return 'worlds.html?world='+encodeURIComponent(p.world)+(p.mapPlace?'#place='+encodeURIComponent(p.mapPlace):'');}
 function eligible(q){return q.rewards.filter(r=>r.kind==='lead'?$('include-leads').checked:['completion','choice','unlock'].includes(r.kind)||$('reward-scope').value==='all');}
 function questValues(q,k){if(k==='batch')return[q.batch||'Original collection'];if(k==='start')return[q.start.area];if(k==='world')return[q.start.world];if(k==='destination')return [...new Set(q.destinations.map(p=>p.world))];if(k==='kind')return[q.kind];if(k==='mod')return[q.mod];if(k==='status')return[state(q.id).status];return[];}
 function matches(q,except=null){
  if(!norm($('quest-search').value).trim().split(/\s+/).filter(Boolean).every(t=>q.search.includes(t)))return false;
  if($('hide-completed').checked&&state(q.id).status==='Completed')return false;
  if($('known-start').checked&&(q.start.known===false||q.start.area==='Starting area pending'||q.id==='Q015'))return false;
  for(const [k,s]of Object.entries(selected)){if(k===except||!s.size||itemGroups.has(k))continue;if(!questValues(q,k).some(v=>s.has(v)))return false;}
  const tests=Object.entries(selected).filter(([k,s])=>k!==except&&s.size&&itemGroups.has(k));
  if(tests.length||$('wanted-only').checked){const ok=eligible(q).some(r=>tests.every(([k,s])=>(r.tags[k]||[]).some(v=>s.has(v)))&&(!$('wanted-only').checked||(r.catalog&&picks[r.catalog]==='Want')));if(!ok)return false;}
  return true;
 }
 function values(q,k){return itemGroups.has(k)?[...new Set(eligible(q).flatMap(r=>r.tags[k]||[]))]:questValues(q,k);}
 function draw(){
  filtered=quests.filter(q=>matches(q));const sort=$('quest-sort').value;
  filtered.sort((a,b)=>sort==='name'?a.title.localeCompare(b.title):sort==='start'?a.start.area.localeCompare(b.start.area)||a.title.localeCompare(b.title):sort==='mod'?a.lo-b.lo||a.index-b.index:sort==='progress'?statuses.indexOf(state(a.id).status)-statuses.indexOf(state(b.id).status)||a.index-b.index:a.index-b.index);
  const ids=new Set(filtered.map(q=>q.id));for(const q of quests){const c=cards.get(q.id);c.hidden=!ids.has(q.id);c.dataset.status=state(q.id).status;c.querySelector('.status-badge').textContent=state(q.id).status+(state(q.id).rewardCollected?' · rewards collected':'');}
  const frag=document.createDocumentFragment();filtered.forEach(q=>frag.append(cards.get(q.id)));$('quest-cards').append(frag);
  $('quest-count').textContent=filtered.length+' / '+quests.length+' cards shown';$('quest-empty').hidden=!!filtered.length;
  $('quest-stats').replaceChildren(...[quests.length+' quests & adventure guides',quests.filter(q=>state(q.id).status==='In progress').length+' in progress',quests.filter(q=>state(q.id).status==='Completed').length+' completed'].map(t=>node('span','',t)));
  for(const c of checks)c.count.textContent=quests.filter(q=>matches(q,c.group)&&values(q,c.group).includes(c.value)).length;
  const active=$('active-filters');active.replaceChildren();let n=0;for(const [group,set]of Object.entries(selected))for(const value of set){n++;const b=node('button','chip',(realms[value]||value)+' ×');b.type='button';b.setAttribute('aria-label','Remove '+(realms[value]||value)+' filter');b.onclick=()=>{set.delete(value);checks.find(c=>c.group===group&&c.value===value).input.checked=false;draw();};active.append(b);}
  $('filter-count').textContent=n?'· '+n+' active':'';
 }
 function reset(){for(const set of Object.values(selected))set.clear();checks.forEach(c=>c.input.checked=false);for(const id of ['include-leads','wanted-only','hide-completed','known-start'])$(id).checked=false;$('quest-search').value='';$('reward-scope').value='end';$('quest-sort').value='curated';draw();}
 function rewardRow(r){
  const a=node('article','reward-row');a.dataset.kind=r.kind;if(r.catalog)a.dataset.catalog=r.catalog;a.append(node('span','kind-label',labels[r.kind]),node('h5','',(r.catalog?r.catalog+' · ':'')+r.label));if(r.note)a.append(node('p','',r.note));
  if(r.catalog){const item=catalog.get(r.catalog).raw;a.append(node('p','',item['Effect / interest']));const audit=SaqrimTags.auditNode(item);if(audit)a.append(audit);const d=node('details');d.append(node('summary','','Location, evidence & item source'),node('p','',item['Where / unlock']),node('p','hint',item['Evidence status']),node('p','hint',item.Qualifications));const links=node('div','quest-links');addLink(links,'./#'+r.catalog,'Full item entry →');addLink(links,'map.html#'+r.catalog,'Item map / location index');d.append(links);a.append(d);}
  return a;
 }
 function makeCard(q){
  const card=node('details','quest-card');card.id=q.id;const summary=node('summary'),meta=node('div','card-meta');meta.append(node('span','qid',q.id),node('span','',q.kind),node('span','status-badge',state(q.id).status));summary.append(meta,node('h3','',q.title),node('p','quest-mod','#'+q.lo+' · '+q.mod),node('p','hook',q.hook),node('p','start-preview','START · '+(realms[q.start.world]||q.start.world)+' / '+q.start.area+' · '+q.start.place));
  const end=q.rewards.filter(r=>['completion','choice','unlock'].includes(r.kind));summary.append(node('p','reward-preview',end.length?'AT THE END · '+end.map(r=>r.label).join(' · '):'FINAL PAYOUT · Not yet documented in this guide'),node('span','open-label','Open start, rewards & your progress ↓'));card.append(summary);
  const body=node('div','quest-body'),box=node('section','progress-box');const label=node('label','','My quest progress'),status=node('select');status.id='status-'+q.id;label.htmlFor=status.id;for(const s of statuses){const o=node('option','',s);o.value=s;status.append(o);}status.value=state(q.id).status;label.append(status);box.append(label);
  const tick=node('label','tick'),collected=node('input');collected.type='checkbox';collected.id='reward-'+q.id;collected.checked=state(q.id).rewardCollected===true;tick.append(collected,document.createTextNode('My chosen rewards collected'));box.append(tick,node('p','hint','Manual checklist—not proof of every possible reward. Independent of quest completion and your Want list.'));
  const form=node('form'),nl=node('label','','My notes'),notes=node('textarea'),b=node('button','','Save note');notes.id='notes-'+q.id;nl.htmlFor=notes.id;notes.maxLength=3000;notes.placeholder='What to revisit, what you chose, where you stored it…';notes.value=state(q.id).notes||'';nl.append(notes);b.type='submit';form.append(nl,b);box.append(form);
  const set=fields=>{progress[q.id]={...state(q.id),...fields};save();draw();};status.onchange=()=>set({status:status.value});collected.onchange=()=>set({rewardCollected:collected.checked});form.onsubmit=e=>{e.preventDefault();set({notes:notes.value});message(q.id+' note '+(storageOK?'saved.':'kept for this visit; back up before leaving.'));};body.append(box);
  body.append(node('h4','','Where to start'),node('p','',q.start.place),node('p','',q.start.trigger));const startLinks=node('div','quest-links'),u=mapURL(q.start);if(u)addLink(startLinks,u,q.start.precision==='nearby'?'Show nearby landmark (not exact start) →':q.start.precision==='hub'?'Show starting town / hub →':'Show starting area / world guide →');else startLinks.append(node('span','hint','No calibrated start pin. Use the instructions and sources, not a guessed marker.'));body.append(startLinks);
  if(q.destinations.length){body.append(node('h4','','Where it takes you'));for(const p of q.destinations){body.append(node('p','',(realms[p.world]||p.world)+' · '+p.place));const url=mapURL(p);if(url){const links=node('div','quest-links');addLink(links,url,'Show destination / world guide →');body.append(links);}}}
  if(q.requirements.length){body.append(node('h4','','Before you go'));q.requirements.forEach(r=>body.append(node('p','',r.kind+': '+r.text)));}
  body.append(node('h4','','At the end · rewards & unlocks'));if(end.length)end.forEach(r=>body.append(rewardRow(r)));else body.append(node('p','hint','No confirmed completion payout is indexed yet. Loot below is not automatically a final reward.'));
  for(const [kind,title]of [['boss','Boss / NPC loot'],['optional','Also worth grabbing'],['lead','Unverified leads · not guaranteed rewards']]){const rows=q.rewards.filter(r=>r.kind===kind);if(!rows.length)continue;const d=node('details','loot-group');d.dataset.group=kind;d.append(node('summary','',title+' · '+rows.length));rows.forEach(r=>d.append(rewardRow(r)));body.append(d);}
  if(q.spoilers){const d=node('details','outcome-spoilers');d.append(node('summary','','Reveal outcome / choice spoilers'),node('p','',q.spoilers));body.append(d);}
  if(q.chain.length){body.append(node('h4','','Connected quests'));const links=node('div','quest-links');q.chain.forEach(id=>addLink(links,'quests.html#'+id,quests.find(t=>t.id===id).title));body.append(links);}
  q.notes.forEach(t=>body.append(node('p','hint',t)));
  body.append(node('p','hint','Linked item records retain their original sources and PS5/version/override qualifications. No final load-order behavior has been play-tested by this guide.'));
  const sources=node('details','sources');sources.append(node('summary','','Sources & verification'));q.sources.forEach(s=>{addLink(sources,s.url,s.label);sources.append(node('small','',s.scope));});body.append(sources);
  const links=node('div','quest-links');addLink(links,'quests.html#'+q.id,'Link to this quest');addLink(links,'load-order.html#mod-'+String(q.lo).padStart(3,'0'),'Recorded source mod #'+q.lo);body.append(links);card.append(body);return card;
 }
 function sanitize(obj,partial=false){const out={};if(!obj||typeof obj!=='object'||Array.isArray(obj))throw Error('Expected a quest-progress object.');for(const q of quests){if(!Object.prototype.hasOwnProperty.call(obj,q.id))continue;const v=obj[q.id];if(!v||typeof v!=='object'||Array.isArray(v))continue;const f={};if(statuses.includes(v.status))f.status=v.status;if(typeof v.rewardCollected==='boolean')f.rewardCollected=v.rewardCollected;if(typeof v.notes==='string')f.notes=v.notes.slice(0,3000);if(Object.keys(f).length)out[q.id]=partial?f:{status:'Not started',rewardCollected:false,notes:'',...f};}return out;}
 function syncControls(){for(const q of quests){$('status-'+q.id).value=state(q.id).status;$('reward-'+q.id).checked=state(q.id).rewardCollected;if(document.activeElement!==$('notes-'+q.id))$('notes-'+q.id).value=state(q.id).notes;}}
 function backup(){return JSON.stringify({format:'saqrim-quest-progress',version:1,exportedAt:new Date().toISOString(),quests:progress},null,2);}
 function importProgress(raw){if(typeof raw!=='string'||raw.length>2*1024*1024)throw Error('Backup is too large.');const d=JSON.parse(raw);if(!d||d.format!=='saqrim-quest-progress'||d.version!==1)throw Error('Use a Saqrim quest-progress backup. Item-choice backups belong in the Loot catalog.');const incoming=sanitize(d.quests,true);if(!Object.keys(incoming).length)throw Error('No recognized quest progress found.');for(const [id,v]of Object.entries(incoming))progress[id]={...state(id),...v};save();syncControls();draw();message('Imported '+Object.keys(incoming).length+' quest records. Other saves were not changed.');}
 function transfer(importing){$('quest-transfer').hidden=false;$('transfer-title').textContent=importing?'Import quest progress':'Back up quest progress';$('transfer-text').value=importing?'':backup();$('transfer-text').readOnly=!importing;for(const id of ['copy-backup','save-backup'])$(id).hidden=importing;for(const id of ['apply-import','import-file-label'])$(id).hidden=!importing;$('quest-transfer').scrollIntoView({behavior:'instant',block:'start'});}
 function selectedURL(){const p=new URLSearchParams();for(const [k,s]of Object.entries(selected))for(const v of s)p.append(k,v);if($('quest-search').value)p.set('q',$('quest-search').value);p.set('scope',$('reward-scope').value);p.set('sort',$('quest-sort').value);for(const id of ['include-leads','wanted-only','hide-completed','known-start'])if($(id).checked)p.set(id,'1');return new URL('quests.html?'+p,location.href).href;}
 function openHash(){let id;try{id=decodeURIComponent(location.hash.slice(1));}catch(_){return;}const card=cards.get(id);if(!card)return;reset();card.open=true;requestAnimationFrame(()=>card.scrollIntoView({block:'start',behavior:'instant'}));}
 try{
  const [a,b]=await Promise.all([fetch('quests-data.json?v=3'),fetch('catalog-current.html?v=1')]);if(!a.ok||!b.ok)throw Error('Data request failed.');const pack=await a.json(),doc=new DOMParser().parseFromString(await b.text(),'text/html'),raw=JSON.parse(doc.getElementById('dataset').textContent);if(raw.length!==633||new Set(raw.map(r=>r['Catalog ID'])).size!==633)throw Error('Original catalog integrity failure.');
  catalog=new Map(raw.map(r=>[r['Catalog ID'],{raw:r,tags:SaqrimTags.classify(r).tags}]));const rg=SaqrimTags.groups.filter(([k])=>k!=='choice');
  quests=pack.quests.map((q,index)=>{const rewardRows=(q.rewards||[]).map(r=>({...r,...(pack.catalogLinks?.[q.id]?.[r.label]||{})}));if(q.rewardMod)for(const r of raw)if(Number(r['LO #'])===q.rewardMod.lo)rewardRows.push({catalog:r['Catalog ID'],kind:(q.rewardMod.boss||[]).includes(r['Catalog ID'])?'boss':q.rewardMod.kind,note:q.rewardMod.note});return{requirements:[],notes:[],chain:[],sources:[],destinations:[],...q,index,rewards:rewardRows.map(r=>{if(r.catalog&&!catalog.has(r.catalog))throw Error('Unknown catalog ID '+r.catalog);if(!labels[r.kind])throw Error('Unknown reward role');return{...r,label:r.label||catalog.get(r.catalog).raw.Target,tags:{...Object.fromEntries(rg.map(([k])=>[k,[]])),...(r.catalog?catalog.get(r.catalog).tags:{}),...r.tags}};})};});
  if(quests.length!==46||new Set(quests.map(q=>q.id)).size!==quests.length)throw Error('Quest collection integrity failure.');for(const q of quests){if(q.chain.some(id=>!quests.some(v=>v.id===id)))throw Error('Unknown linked quest');q.search=norm([q.id,q.title,q.mod,q.hook,JSON.stringify(q.start),JSON.stringify(q.destinations),...q.rewards.map(r=>[r.catalog,r.label,Object.values(r.tags).flat().join(' ')].join(' '))].join(' '));}
  progress=sanitize(read(KEY));picks=read(PICK);
  groups=[['batch','Quest collection',['Original collection','Expansion 2']],['start','Starting area',[...new Set(quests.map(q=>q.start.area))].sort()],['world','Starting world',[...new Set(quests.map(q=>q.start.world))]],['destination','Destination world',[...new Set(quests.flatMap(q=>q.destinations.map(p=>p.world)))]],['kind','Quest / guide type',[...new Set(quests.map(q=>q.kind))]],['status','My progress',statuses],['mod','Installed mod',[...new Set(quests.map(q=>q.mod))].sort()],...rg];
  for(const [group,title,vals]of groups){selected[group]=new Set();const d=node('details','facet');d.open=['batch','start','category'].includes(group);d.append(node('summary','',title));const fs=node('fieldset');fs.append(node('legend','',title));for(const value of vals){const label=node('label','tick'),input=node('input'),count=node('span','n');input.type='checkbox';input.dataset.group=group;input.value=value;input.onchange=()=>{if(input.checked)selected[group].add(value);else selected[group].delete(value);draw();};label.append(input,node('span','',realms[value]||value),count);fs.append(label);checks.push({group,value,input,count});}d.append(fs);$('quest-facets').append(d);}
  for(const q of quests){const card=makeCard(q);cards.set(q.id,card);$('quest-cards').append(card);}
  for(const id of ['quest-search','quest-sort','reward-scope','include-leads','wanted-only','hide-completed','known-start'])$(id).addEventListener(id==='quest-search'?'input':'change',draw);
  $('clear-filters').onclick=reset;$('show-results').onclick=()=>{if(innerWidth<=760)$('quest-filters').open=false;$('quest-results').scrollIntoView({behavior:'instant'});};
  $('backup-quests').onclick=()=>transfer(false);$('import-quests').onclick=()=>transfer(true);$('close-transfer').onclick=()=>$('quest-transfer').hidden=true;$('apply-import').onclick=()=>{try{importProgress($('transfer-text').value);}catch(e){message('Import failed: '+e.message);}};
  $('quest-import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2*1024*1024)throw Error('Backup is too large.');importProgress(await f.text());}catch(err){message('Import failed: '+err.message);}e.target.value='';};
  $('copy-backup').onclick=async()=>{try{await navigator.clipboard.writeText($('transfer-text').value);message('Backup copied.');}catch(_){$('transfer-text').select();message('Text selected. Use your device’s Copy command.');}};
  $('save-backup').onclick=()=>{const u=URL.createObjectURL(new Blob([backup()],{type:'application/json'})),a=node('a');a.href=u;a.download='Saqrim_Quest_Progress.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);};
  $('share-filters').onclick=async()=>{const u=selectedURL();try{await navigator.clipboard.writeText(u);message('View link copied. It shares filters, not personal progress or notes. Want/progress filters use the recipient’s own saves.');}catch(_){message('Copy this view link: '+u);}};
  const params=new URLSearchParams(location.search);for(const c of checks)if(params.getAll(c.group).includes(c.value)){selected[c.group].add(c.value);c.input.checked=true;}$('quest-search').value=params.get('q')||'';if(params.get('scope')==='all')$('reward-scope').value='all';if([...$('quest-sort').options].some(o=>o.value===params.get('sort')))$('quest-sort').value=params.get('sort');for(const id of ['include-leads','wanted-only','hide-completed','known-start'])$(id).checked=params.get(id)==='1';
  if(innerWidth<=760)$('quest-filters').open=false;saveNote();draw();window.addEventListener('hashchange',openHash);window.addEventListener('storage',e=>{if(e.key===PICK||e.key===null)picks=read(PICK);if(e.key===KEY||e.key===null){progress=sanitize(read(KEY));syncControls();}draw();});
  window.SaqrimQuests={quests,catalog,selected,reset,render:draw,backup,importProgress,mapURL,selectedURL,get filtered(){return filtered;},get progress(){return progress;}};openHash();
 }catch(e){$('quest-error').hidden=false;$('quest-stats').textContent='Quest journal unavailable.';console.error(e);}
})();
