"""Regression tests against the actual, self-hosted map and immutable catalog."""
import contextlib, functools, hashlib, http.server, json, os, pathlib, threading
from playwright.sync_api import sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]
class Quiet(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args): pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Quiet,directory=str(ROOT)))
threading.Thread(target=server.serve_forever,daemon=True).start()
URL=f'http://127.0.0.1:{server.server_port}'
checks=[]
def check(name,value):
    assert value,name
    checks.append(name);print('PASS',name,flush=True)
with sync_playwright() as p:
    browser=p.chromium.launch()
    context=browser.new_context(viewport={'width':1440,'height':1000})
    page=context.new_page(); errors=[]; external=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:external.append(r.url) if not r.url.startswith(URL) else None)
    page.goto(URL+'/map.html');page.wait_for_function('window.SaqrimMap && document.querySelector(".leaflet-image-layer")?.naturalWidth===4096')
    check('633 catalog records retained',page.evaluate('SaqrimMap.records.length===633'))
    check('364 distinct reference places',page.evaluate('SaqrimMap.places.length===364 && new Set(SaqrimMap.places.map(p=>p.name)).size===364'))
    check('103 records / 44 areas linked',page.evaluate('SaqrimMap.linkedCount===103 && SaqrimMap.linkedPlaceCount===44'))
    check('known map markers rendered',page.locator('.leaflet-marker-icon').count()>50)
    check('self-hosted image loaded',page.locator('.leaflet-image-layer').evaluate('(n)=>n.naturalHeight===3072'))
    check('north-positive coordinate orientation',page.evaluate('SaqrimMap.places.find(p=>p.name==="Solitude").latlng[0]>SaqrimMap.places.find(p=>p.name==="Whiterun").latlng[0]'))
    check('no remote runtime requests',not external)
    check('no horizontal desktop overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.fill('#map-search','Ironbind');check('Ironbind filters to exactly one place',page.evaluate('SaqrimMap.visiblePlaces.length===1 && SaqrimMap.visiblePlaces[0].name==="Ironbind Barrow"'))
    page.evaluate('SaqrimMap.selectPlace("Ironbind Barrow",{focus:false})')
    check('Skull Commander and Fiery Souls appear',page.locator('#details [data-item="W012"]').count()==1 and page.locator('#details [data-item="W180"]').count()==1)
    check('interior direction retained','spiral staircase' in page.locator('#details').inner_text())
    check('area caveat explicit','not an exact' in page.locator('#details').inner_text())
    page.evaluate('SaqrimMap.reset()');page.click('#items-tab');page.fill('#map-search','W552')
    check('unmapped record searchable',page.locator('#location-index .list-row').count()==1)
    page.locator('#location-index .list-row').click()
    check('Evergloam coordinates not fabricated',page.evaluate('SaqrimMap.records.find(r=>r.id==="W552").links.length===0'))
    check('unmapped item has original directions','Plankside' in page.locator('#details').inner_text())
    page.evaluate('SaqrimMap.reset()');page.select_option('#world','Evergloam')
    check('other worlds stay in index, not on mainland',page.evaluate('SaqrimMap.filteredItems.length===22 && SaqrimMap.visiblePlaces.length===0'))
    page.select_option('#world','');page.check('#unpinned-only')
    check('all 530 unpinned notes available',page.evaluate('SaqrimMap.filteredItems.length===530 && SaqrimMap.filteredItems.length===SaqrimMap.records.filter(r=>!r.links.length).length'))
    page.evaluate('SaqrimMap.reset()');page.locator('#map-filters').evaluate('(n)=>n.open=true');page.locator('.facet').evaluate_all('(ns)=>ns.forEach(n=>n.open=true)')
    page.check('input[data-group="slot"][value="Ring"]')
    check('ring checkbox filters records',page.evaluate('SaqrimMap.filteredItems.length>0 && SaqrimMap.filteredItems.every(r=>r.meta.tags.slot.includes("Ring"))'))
    page.check('input[data-group="slot"][value="Amulet / necklace"]')
    check('same group uses OR',page.evaluate('SaqrimMap.filteredItems.some(r=>r.meta.tags.slot.includes("Ring")) && SaqrimMap.filteredItems.some(r=>r.meta.tags.slot.includes("Amulet / necklace"))'))
    page.evaluate('SaqrimMap.reset()');page.check('input[data-group="school"][value="Illusion"]')
    check('spell school filter applied',page.evaluate('SaqrimMap.filteredItems.length>0 && SaqrimMap.filteredItems.every(r=>r.meta.tags.school.includes("Illusion"))'))
    page.check('input[data-group="school"][value="Conjuration"]');page.check('input[data-group="category"][value="Spells / summons"]')
    check('checkbox groups combine correctly',page.evaluate('SaqrimMap.filteredItems.every(r=>r.meta.tags.category.includes("Spells / summons") && r.meta.tags.school.some(s=>["Illusion","Conjuration"].includes(s)))'))
    page.evaluate('SaqrimMap.reset()');page.check('input[data-group="place"][value="Cities"]')
    check('known place type filter',page.evaluate('SaqrimMap.visiblePlaces.length===9'))
    page.evaluate('SaqrimMap.reset();localStorage.setItem("skyrimLootChoices_v202_20260917",JSON.stringify({W012:"Want",W552:"Maybe",W180:"Skip"}));localStorage.setItem("saqrimObservedStats_v1",JSON.stringify({W012:{armor:500}}));localStorage.setItem("saqrim-load-order-220-2026-09-17","[1,2,3]")')
    before=page.evaluate('JSON.stringify({...localStorage})');page.reload();page.wait_for_function('window.SaqrimMap')
    page.locator('#map-filters').evaluate('(n)=>n.open=true');page.check('#picks-only')
    check('legacy picks readable',page.evaluate('SaqrimMap.filteredItems.map(r=>r.id).sort().join(",")==="W012,W552"'))
    check('unknown pick not pinned',page.evaluate('SaqrimMap.visiblePlaces.length===1 && SaqrimMap.visiblePlaces[0].name==="Ironbind Barrow"'))
    check('map never writes user storage',before==page.evaluate('JSON.stringify({...localStorage})'))
    page.evaluate('SaqrimMap.reset()');page.locator('#map-filters').evaluate('(n)=>n.open=false')
    z=page.evaluate('SaqrimMap.map.getZoom()');page.locator('.map-pin.cluster').first.click()
    check('cluster expands by zooming',page.evaluate('SaqrimMap.map.getZoom()')>z)
    page.click('#large-map');check('larger map toggle',page.evaluate('document.body.classList.contains("map-expanded")'))
    page.keyboard.press('Escape');check('Escape leaves larger map',not page.evaluate('document.body.classList.contains("map-expanded")'))
    page.goto(URL+'/map.html#W616');page.wait_for_selector('#details [data-item="W616"]')
    page.evaluate('SaqrimMap.selectPlace("Dawnstar",{focus:false})');check('nearby town not false exact merchant location','NOT the pickup spot' in page.locator('#details').inner_text())
    page.goto(URL+'/map.html#place=Ironbind%20Barrow');page.wait_for_selector('#details [data-item="W012"]');check('place deep link supported',page.locator('#details h2').inner_text()=='Ironbind Barrow')
    page.goto(URL+'/#W012');page.wait_for_function('window.SaqrimCatalog')
    check('original catalog deep link works',page.locator('#W012').get_attribute('open') is not None)
    check('catalog map tab added once',page.locator('.nav a[href="map.html"]').count()==1)
    check('catalog item links back to map/index',page.locator('#W012 .saqrim-map-link a').get_attribute('href')=='map.html#W012')
    check('catalog preserved at 633',page.evaluate('SaqrimCatalog.records.length===633'))
    page.goto(URL+'/load-order.html');page.wait_for_selector('#mods .row');check('220 load order records preserved',page.locator('#mods .row').count()==220)
    check('load order map tab added once',page.locator('.nav a[href="map.html"]').count()==1)
    check('existing added checklist preserved',page.locator('#added-count').inner_text().startswith('3 / 220'))
    page.set_viewport_size({'width':390,'height':844});page.goto(URL+'/map.html');page.wait_for_function('window.SaqrimMap')
    check('no horizontal mobile overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.evaluate('SaqrimMap.selectItem("W552",{focus:false})');check('detail card fits mobile',page.locator('#details').evaluate('(n)=>n.getBoundingClientRect().right<=innerWidth'))
    page.evaluate('scrollTo(0,1500)');page.wait_for_function('!document.getElementById("saqrim-top").hidden');page.click('#saqrim-top');check('Top jumps instantly',page.evaluate('scrollY')==0)
    (ROOT/'test-results').mkdir(exist_ok=True)
    page.screenshot(path=str(ROOT/'test-results/map-mobile.png'),full_page=True)
    page.set_viewport_size({'width':1440,'height':1000});page.goto(URL+'/map.html');page.wait_for_function('window.SaqrimMap && document.querySelector(".leaflet-image-layer")?.naturalWidth===4096');page.screenshot(path=str(ROOT/'test-results/map-desktop.png'),full_page=True)
    check('no browser JavaScript errors',not errors)
    print('RESULT',json.dumps({'checks':len(checks),'errors':errors,'linked':103,'places':364}),flush=True)
    browser.close()
server.shutdown()
