"""Exercise actual site files, including unchanged catalog and load-order integration."""
import functools, http.server, json, pathlib, subprocess, threading
from playwright.sync_api import sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]
BASE='cb85293f39ca5331c90a93aaf816f16aa80dae92'
checks=[]
def check(name,value):
    assert value,name
    checks.append(name); print('PASS',name,flush=True)
for name in ['catalog-source.html','catalog-tags.js','catalog.js','load-order.tsv','load-order.js','map.js','map-links.js','map-locations.json','world-data.js','worlds.js']:
    old=subprocess.check_output(['git','show',BASE+':'+name],cwd=ROOT)
    check('preserved '+name,(ROOT/name).read_bytes()==old)
class Quiet(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args): pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Quiet,directory=str(ROOT)))
threading.Thread(target=server.serve_forever,daemon=True).start()
URL=f'http://127.0.0.1:{server.server_port}'
with sync_playwright() as p:
    browser=p.chromium.launch();context=browser.new_context(viewport={'width':1440,'height':960})
    page=context.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    def go(path='quests.html'):
        page.goto(URL+'/'+path);page.wait_for_function('window.SaqrimQuests')
    def ev(s):return page.evaluate(s)
    def expand():
        page.locator('#quest-filters').evaluate('(n)=>n.open=true');page.locator('.facet').evaluate_all('(ns)=>ns.forEach(n=>n.open=true)')
    def reset():ev('SaqrimQuests.reset()');expand()
    def found():return ev('SaqrimQuests.filtered.map(q=>q.id)')
    go()
    check('46 distinct quest cards',ev('SaqrimQuests.quests.length===46&&new Set(SaqrimQuests.quests.map(q=>q.id)).size===46'))
    check('all 617 original catalog records available',ev('SaqrimQuests.catalog.size===617'))
    check('all W-number links resolve',ev('SaqrimQuests.quests.every(q=>q.rewards.every(r=>!r.catalog||SaqrimQuests.catalog.has(r.catalog)))'))
    check('manual reward tags match existing filter vocabulary',ev('SaqrimQuests.quests.every(q=>q.rewards.every(r=>Object.entries(r.tags).every(([k,v])=>v.every(x=>SaqrimTags.groups.find(g=>g[0]===k)[2].includes(x)))))'))
    check('new navigation present once',page.locator('.nav a[href="quests.html"]').count()==1)
    check('desktop has no horizontal overflow',ev('document.documentElement.scrollWidth<=innerWidth'))
    reset();page.fill('#quest-search','Miasma');page.check('input[data-group="school"][value="Destruction"]')
    check('route tome is not a final reward',found()==[])
    page.select_option('#reward-scope','all');check('include route loot finds Miasmic Cloud',found()==['Q001'])
    page.check('input[data-group="weapon"][value="Bow"]');check('same reward must match all item facets',found()==[])
    reset();page.check('input[data-group="start"][value="Markarth"]');check('filter starting area',set(found())=={'Q018','Q028','Q041'})
    page.check('input[data-group="start"][value="Falkreath"]');check('same group uses OR',set(found())=={'Q018','Q022','Q025','Q028','Q041'})
    page.check('input[data-group="slot"][value="Ring"]');check('ring rewards from both areas',set(found())=={'Q018','Q022','Q041'})
    page.check('input[data-group="armor"][value="Light armor"]');check('separate ring and armor cannot create false match',found()==[])
    reset();page.fill('#quest-search','Siege at Icemoth');page.check('input[data-group="world"][value="skyrim"]');page.check('input[data-group="destination"][value="icemoth"]');check('start world differs from destination',found()==['Q007'])
    reset();page.fill('#quest-search','It Came from Akavir');page.check('input[data-group="category"][value="Armor / clothing"]');check('unverified gear excluded by default',found()==[])
    page.check('#include-leads');check('unverified reward filters require opt-in',found()==['Q008'])
    check('NPC outfit is not promised as a reward',ev('SaqrimQuests.quests.find(q=>q.id==="Q008").rewards.every(r=>r.catalog!=="W617")'))
    check('adventure rosters retain all 22 and 50 records',ev('SaqrimQuests.quests.find(q=>q.id==="Q013").rewards.length===22&&SaqrimQuests.quests.find(q=>q.id==="Q015").rewards.length===50'))
    ev('localStorage.setItem("skyrimLootChoices_v202_20260917",JSON.stringify({W541:"Want",W014:"Maybe",W170:"Want"}));localStorage.setItem("saqrimObservedStats_v1",JSON.stringify({W012:{armor:500}}));localStorage.setItem("saqrim-load-order-220-2026-09-17","[1,2,3]")')
    old=ev('JSON.stringify([localStorage.getItem("skyrimLootChoices_v202_20260917"),localStorage.getItem("saqrimObservedStats_v1"),localStorage.getItem("saqrim-load-order-220-2026-09-17")])')
    go();expand();page.check('#wanted-only');check('Want list reads existing choices with final-reward scope',found()==['Q017'])
    page.select_option('#reward-scope','all');check('Want list plus route loot includes Icemoth',set(found())=={'Q007','Q017'})
    go('quests.html#Q017');page.wait_for_selector('#Q017[open]');page.select_option('#status-Q017','Completed');check('completion does not collect reward',not page.is_checked('#reward-Q017'))
    page.check('#reward-Q017');page.fill('#notes-Q017','<img src=x onerror=alert(1)> Kept at home.');page.locator('#Q017 form button').click()
    go('quests.html#Q017');page.wait_for_selector('#Q017[open]');check('progress and note persist on reload',page.input_value('#status-Q017')=='Completed' and page.is_checked('#reward-Q017') and 'Kept' in page.input_value('#notes-Q017'))
    check('personal note treated as text, not markup',page.locator('#Q017 img').count()==0)
    page.select_option('#status-Q017','In progress');check('reward collection stays independent',page.is_checked('#reward-Q017'))
    check('quest backup has separate format',json.loads(ev('SaqrimQuests.backup()'))['format']=='saqrim-quest-progress')
    page.evaluate('(raw)=>SaqrimQuests.importProgress(raw)',json.dumps({'format':'saqrim-quest-progress','version':1,'quests':{'Q017':{'status':'Completed'},'Q999':{'notes':'ignore'}}}))
    check('partial import preserves note and reward',ev('SaqrimQuests.progress.Q017.rewardCollected&&SaqrimQuests.progress.Q017.notes.includes("Kept")&&!SaqrimQuests.progress.Q999'))
    check('item backup rejected by quest importer',ev('(()=>{try{SaqrimQuests.importProgress(JSON.stringify({format:"skyrim-loot-choices",choices:{W541:"Skip"}}));return false;}catch(e){return true;}})()'))
    check('old item, stat and console saves unchanged',old==ev('JSON.stringify([localStorage.getItem("skyrimLootChoices_v202_20260917"),localStorage.getItem("saqrimObservedStats_v1"),localStorage.getItem("saqrim-load-order-220-2026-09-17")])'))
    reset();page.check('#hide-completed');check('hide completed quests', 'Q017' not in found())
    go('quests.html?start=Markarth');check('shareable area-filter URL',set(found())=={'Q018','Q028','Q041'})
    check('outcome spoilers start collapsed',page.locator('#Q018 .outcome-spoilers').get_attribute('open') is None)
    go('quests.html#Q001');check('recorded mod hash zero-padded',page.locator('#Q001 a[href="load-order.html#mod-014"]').count()==1)
    linked=ev('new Set(SaqrimQuests.quests.flatMap(q=>q.rewards.map(r=>r.catalog).filter(Boolean))).size')
    page.goto(URL+'/');page.wait_for_function('window.SaqrimCatalog');page.wait_for_selector('#W541 .quest-catalog-links',state='attached')
    check('catalog links back to the quest',page.locator('#W541 .quest-catalog-links a[href="quests.html#Q017"]').count()==1)
    check('adventure expansion has reverse catalog links',page.locator('#W552 .quest-catalog-links a[href="quests.html#Q013"]').count()==1)
    page.goto(URL+'/load-order.html#mod-014');page.wait_for_selector('#mod-014');check('all 220 load-order entries retained',page.locator('#mods .row').count()==220)
    check('console checklist progress retained',page.locator('#added-count').inner_text().startswith('3 / 220'))
    page.wait_for_selector('.nav a[href="quests.html"]');check('load-order quest navigation present once',page.locator('.nav a[href="quests.html"]').count()==1)
    page.goto(URL+'/map.html#place=Markarth');page.wait_for_function('window.SaqrimQuestMap');page.wait_for_selector('#details .quest-starts')
    check('map place lists starting quest',page.locator('#details .quest-starts a[href="quests.html#Q018"]').count()==1)
    check('quest-start map overlay rendered',page.locator('.quest-start-icon').count()>0)
    page.uncheck('#show-quest-starts');check('quest marker toggle independent',page.locator('.quest-start-icon').count()==0)
    page.check('#show-quest-starts');check('pending starts have no fabricated pins',ev('SaqrimQuestMap.candidates().every(q=>!!q.start.mapPlace)'))
    page.fill('#map-search','It Came from Akavir');page.wait_for_function('document.querySelectorAll(".quest-start-icon").length===1')
    check('quest-name search finds the start',page.locator('.quest-start-icon').count()==1)
    page.locator('.quest-start-icon').click();check('nearby landmark caveat in popup','nearby reference' in page.locator('.leaflet-popup').inner_text())
    # Optional realm artwork remains host-dependent; test integration with it unavailable.
    page.route('https://images.uesp.net/**',lambda route:route.abort())
    page.goto(URL+'/worlds.html?world=solstheim#place=Raven%20Rock');page.wait_for_function('window.SaqrimQuestMap');page.wait_for_selector('#selection .quest-starts')
    check('Solstheim start links to Miasma',page.locator('#selection .quest-starts a[href="quests.html#Q001"]').count()==1)
    check('realm quest marker rendered',page.locator('.quest-start-icon').count()==3)
    page.select_option('#map-world','icemoth');page.wait_for_function('document.querySelectorAll(".quest-start-icon").length===0');check('other-world start pins do not leak across maps',page.locator('.quest-start-icon').count()==0)
    page.set_viewport_size({'width':390,'height':844});go('quests.html#Q001');page.wait_for_selector('#Q001[open]');check('phone has no horizontal overflow',ev('document.documentElement.scrollWidth<=innerWidth'))
    check('phone filters start collapsed',page.locator('#quest-filters').get_attribute('open') is None)
    ev('scrollTo(0,1800)');page.wait_for_function('!document.getElementById("saqrim-top").hidden');page.click('#saqrim-top');check('Top button jumps instantly',ev('scrollY===0'))
    out=ROOT/'test-results';out.mkdir(exist_ok=True);page.screenshot(path=str(out/'quests-mobile.png'),full_page=True)
    page.set_viewport_size({'width':1440,'height':960});go('quests.html?start=Markarth');page.locator('#Q018').evaluate('(n)=>n.open=true');page.screenshot(path=str(out/'quests-desktop.png'),full_page=True)
    check('no browser JavaScript errors',not errors)
    result={'checks':len(checks),'errors':errors,'questCards':46,'catalogLinks':linked,'catalogRecords':617,'loadOrderRecords':220}
    (out/'quest-checks.json').write_text(json.dumps(result,indent=2));print('RESULT',json.dumps(result),flush=True);browser.close()
server.shutdown()
