"""Build expansion 2 from the original catalog; no network or console access."""
from pathlib import Path
import json,re
P=Path(__file__).resolve().parents[1]
N='https://www.nexusmods.com/skyrimspecialedition/mods/'
E='https://elderscrolls.fandom.com/wiki/'
G='https://www.gamebanshee.com/skyrim/walkthrough/'
A='Apocalypse - Magic of Skyrim'; J="JaySerpa's Quest Expansion Bundle"; ART='Artificer - An Artifact Overhaul'
qs=[]
def source(url,label,scope='Original author documentation; recorded PS5 behavior not independently tested.'):
 return dict(url=url,label=label,scope=scope)
def start(world,area,place,trigger,mapPlace=None,precision='area',**kw):
 return dict(world=world,area=area,place=place,trigger=trigger,**({'mapPlace':mapPlace,'precision':precision} if mapPlace else {}),**kw)
def dest(world,place,mapPlace=None):return dict(world=world,place=place,**({'mapPlace':mapPlace} if mapPlace else {}))
def reward(label,kind='completion',note='',**tags):
 return dict(label=label,kind=kind,note=note,tags={k:v if isinstance(v,list) else [v] for k,v in tags.items()})
def w(id,kind='optional',note=''): return dict(catalog=id,kind=kind,note=note)
def req(kind,text):return dict(kind=kind,text=text)
def add(title,mod,lo,kind,st,hook,rewards,sources,**kw):
 q=dict(id=f'Q{23+len(qs):03}',title=title,mod=mod,lo=lo,kind=kind,start=st,hook=hook,rewards=rewards,sources=sources,destinations=[])
 q.update(kw);q['batch']='Expansion 2';qs.append(q);return q
book={'category':'Books / powers / other'}
sp=lambda school:{'category':'Spells / summons','school':school}
add('The Breathing Abyss','The Breathing Abyss',148,'Mod quest',start('skyrim','Dawnstar coast','Manias on an island near Yngvild','Speak to Manias; the recorded instructions put his island northeast of Dawnstar.','Yngvild','nearby'),'Follow an investigation into an unsettling underwater cavern.',[reward('Permanent character buff','lead','Added in the author\'s 1.0.6 changelog. Its name and numbers, and inclusion in the recorded v1.00 PS5 port, are not established.',**book)],[source(N+'141216','The Breathing Abyss remake: description and changelog'),source('load-order.html#mod-148','Recorded entry #148','The recording supplies the Manias / Yngvild starting clue.')],destinations=[dest('skyrim','Manias\' investigation / underwater cavern')],notes=['When Manias runs out of dialogue, the recorded instructions say to wait several days.','This is the remake linked by the port, not the older Breathing Abyss release. Yngvild is only a nearby reference.'])
add('Skragmjor — dungeon adventure','Skragmjor',5,'Adventure guide',start('skyrim','Whiterun outskirts','New Nordic ruin west of Whiterun','Find Skragmjor west of Whiterun; the exact approach is not calibrated in this atlas.',known=False),'Explore a newly exposed ruin and a missing-mercenary mystery.',[],[source(N+'139061','Skragmjor: author description and version history')],destinations=[dest('skyrim','Skragmjor')],notes=['The author documents a small flavor quest, not a verified quest title or named unique payout. This card covers the dungeon adventure.','The recorded title/version is Skragmjor v1.0.7. Older documentation calls it Forsaken Crypt.'])
add('Moonpath to Elsweyr — adventure overview','Moonpath to Elsweyr [PS5]',153,'Mod questline',start('skyrim','Falkreath','Khajiit caravan by Falkreath\'s main gate','Look for the caravan. The SSE author moved it outside Falkreath in 1.14b; older versions started inside the Dead Man\'s Drink. The recorded PS5 v1.00 label does not resolve that version difference.','Falkreath','hub'),'Leave Skyrim with a caravan bound for Elsweyr.',[],[source(N+'4341','Moonpath: SSE description and caravan-move changelog'),source('load-order.html#mod-164','Installed Lucien / Moonpath patch','Recorded compatibility addon, not proof of an extra player reward.')],destinations=[dest('elsweyr','Moonpath\'s Elsweyr locations')],notes=['A questline overview, not a claim that every individual Moonpath quest is indexed. The complete ending payout remains undocumented here.','Elsweyr has no calibrated map layer on Saqrim yet. No unrelated realm map is substituted.','Your recorded setup includes the Lucien / Moonpath patch. This guide does not assume Legacy of the Dragonborn or its rewards.'])
lucsource=[source(N+'20035','Lucien: personal-quest FAQ and Intruders / riding documentation')]
add('The Oblivion Engine','Lucien - Fully Voiced Follower',162,'Mod companion quest',start('variable','Traveling with Lucien','Lucien while adventuring together','Recruit Lucien at the Dead Man\'s Drink in Falkreath, travel together, and ask where he wants to visit. His personal quest develops as his relationship with you grows.'),'Investigate a Dwemer mystery with Lucien.',[reward('Lucien\'s research and follow-up quest access','unlock','The later quest Intruders follows completion and re-recruitment; this is not the horse-riding reward.',**book)],lucsource,destinations=[dest('solstheim','Dumzbthar')],chain=['Q027'],notes=['Falkreath is the recruitment location, not a guaranteed place where this quest triggers. Dumzbthar has no calibrated pin here.','Recorded Lucien menu: v1.7.2. Exact PS5 conditions and final override behavior remain untested.'])
add('Intruders','Lucien - Fully Voiced Follower',162,'Mod companion quest',start('variable','Traveling with Lucien','Lucien after returning to the party','After The Oblivion Engine, re-recruit Lucien and listen for his new idle dialogue roughly five in-game days later.'),'Return to Lucien\'s unfinished research.',[reward('Horse riding for Lucien / Clive','unlock','This unlocks riding for Lucien. Clive is his mount, not a new horse awarded to your character.',**book)],lucsource,destinations=[dest('solstheim','Dumzbthar')],requirements=[req('Required quest','The Oblivion Engine (Q026), then re-recruit Lucien.')],chain=['Q026'],notes=['The location where the dialogue fires depends on your travels; no fixed quest-giver pin is invented.'])
add('The Heart of Dibella — expanded',J,145,'Expanded existing quest',start('skyrim','Markarth','Hamal / Temple of Dibella','The expansion offers a non-criminal invitation: become Thane of the Reach and sleep for a courier, or help five people in the Reach. The original inner-sanctum route remains available.','Markarth','hub'),'Help the temple and choose how Dibella\'s favor suits your character.',[reward('Agent of Dibella','completion','The author lets Hamal configure +10% damage against the opposite sex, +10% against the same sex, +5% against both, or no bonus.',**book),w('W362','unlock','Knight of the North documents legitimate ownership of the temple\'s Helm of the Crusader after this quest. It remains a separate pickup.')],[source(N+'94863','JaySerpa: Heart of Dibella expansion'),source('https://www.nexusmods.com/skyrimspecialedition/articles/3005','Knight of the North: relic ownership','Author quest guide, also retained in W362.')],destinations=[dest('skyrim','Fjotra rescue / The Reach')],chain=['Q018','Q032'],notes=['Helping Madanach during Q018 provides an additional peaceful-rescue option in the expansion.','Component confirmed in the recorded v2.6 bundle. Its upstream version and the installed Wintersun patch\'s final behavior remain untested.'])
add('Innocence Lost — expanded',J,145,'Expanded existing quest',start('skyrim','Windhelm','Aventus Aretino\'s house','Talk to Aventus. The expansion also allows investigating Grelod at Honorhall Orphanage in Riften before meeting him.','Windhelm','hub'),'Resolve Aventus\'s plea, with an arrest alternative added by the mod.',[reward('Aretino Family Heirloom','completion','The base-game return-to-Aventus reward; not an enchanted combat item. Alternate-route PS5 payout not separately verified.',**book),reward('Constance / orphanage follow-up','unlock','The expansion adds a follow-up with Constance and an adoption route subject to its requirements.',**book)],[source(N+'80974','JaySerpa: Innocence Lost expansion'),source(E+'Innocence_Lost','Original quest starter and heirloom','Base-game reference; expansion differences are identified separately.')],destinations=[dest('skyrim','Honorhall Orphanage','Riften')],chain=['Q030'],notes=['An arrest route does not automatically rule out the installed Destroy the Dark Brotherhood expansion; that component has its own kidnapping conditions.','Only confirmed bundle components are assumed; no other quest overhaul is silently added.'])
add('Destroy the Dark Brotherhood! — expanded',J,145,'Expanded existing quest',start('skyrim','Hjaalmarch / Dragon Bridge','Astrid\'s Abandoned Shack encounter','Choose the anti-Brotherhood path during Astrid\'s encounter, then follow the report to Commander Maro in Dragon Bridge.','Abandoned Shack','area'),'Hunt the assassins through the expanded investigation.',[reward('Commander Maro\'s gold','completion','The original quest pays 3,000 gold. This amount is a base-game reference, not a measured result from the installed bundle.',**book),reward('Fultheim the Fearless as a potential follower','unlock','Conditional: free him alive, then find him again through the expansion\'s later encounter.',**book),w('W373','boss','Astrid\'s Blade of Woe is loot from her, not Maro\'s final payment.')],[source(N+'118229','JaySerpa: Destroy the Dark Brotherhood expansion'),source(G+'destroythedarkbrotherhood.php','Original quest payout','Base-game walkthrough, not the expansion\'s complete route.')],destinations=[dest('skyrim','Commander Maro','Dragon Bridge'),dest('skyrim','Assassins / Falkreath Sanctuary','Dark Brotherhood Sanctuary')],chain=['Q029'],notes=['The expansion replaces the simple password handoff with an investigation. Do not follow an unmodified walkthrough for that step.','After an Innocence Lost arrest, the expansion\'s alternate kidnapping route also requires the Constance follow-up and killing a vanilla Brotherhood contract target.','Rejecting the Brotherhood is a branching choice, not an additional route through its full membership storyline.'])
add('Infiltration — expanded',J,145,'Expanded existing quest',start('skyrim','The Rift / Treva\'s Watch','Stalleo\'s camp east of Treva\'s Watch','Speak to Stalleo outside the fort.','Treva\'s Watch','nearby'),'Decide how to resolve the dispute over Treva\'s Watch.',[reward('Detect Life spell tome','choice','The original Stalleo success reward. The expansion adds other outcomes; this is not promised for every branch.',**sp('Alteration'))],[source(N+'114054','JaySerpa: Infiltration expansion'),source(G+'infiltration.php','Stalleo camp and original tome reward','Base-game reference; expanded paths differ.')],destinations=[dest('skyrim','Treva\'s Watch and escape tunnel','Treva\'s Watch')],notes=['You can bring Stalleo\'s group along in the expansion. Enter through the escape tunnel rather than rely on the old front-gate shortcut.','The author documents a lasting cleared fort on Stalleo\'s success path. No unrelated Cutting Room Floor patch is assumed.'])
add('Knight of the North — Crusader relic hunt','Knight of the North - Divine Crusader Reworked (PS5)',159,'Adventure guide',start('skyrim','Winterhold coast / Tower Stone','Iceberg Explorer site near the Tower Stone','Read the knight\'s journal and related Thalmor orders. The author recommends this starting point, but the relic hunt can begin with clues at another relic.','The Tower Stone','nearby'),'Follow scattered clues to the Divine Crusader\'s equipment.',[w(f'W{i:03}','optional','A separately placed relic or clue; not a single final turn-in payout.') for i in range(358,366)],[source('https://www.nexusmods.com/skyrimspecialedition/articles/3005','Knight of the North: author quest guide')],destinations=[dest('skyrim','Relic sites across Skyrim')],chain=['Q028','Q042'],notes=['The base Creation\'s Four Skull Lookout shortcut is not this overhaul\'s acquisition route.','The author guide contains conflicting cuirass clues (Northwatch Keep versus a Rorikstead shrine); those remain visible in W364 rather than being silently reconciled.','Heart of Dibella and Wolf Queen Awakened remove ownership restrictions on two separate relics; follow the linked cards.'])
rituals=[
 ('Illusion','Drevis Neloren','100 in standard unpatched references; some guides and patches use 90. The final installed gate is not verified.','Use Vision of the Tenth Eye to find the four hidden College texts.','Hysteria spell tome','Call to Arms, Harmony and Mayhem purchases',[dest('skyrim','Arcanaeum, College halls and Midden','College of Winterhold')],'https://primagames.com/eguides/elder-scrolls-v-skyrim-eguide/quests/quests/ritual-spell-radiant-quests'),
 ('Conjuration','Phinis Gestor','90 Conjuration in the base-game reference.','Complete Phinis\'s unbound-Dremora task and return its Sigil Stone.','Flame Thrall spell tome','Other master Conjuration tome purchases',[dest('skyrim','College rooftop ritual','College of Winterhold')],E+'Conjuration_Ritual_Spell'),
 ('Destruction','Faralda','100 in standard unpatched references; 90 is reported for patched variants. The final installed gate is not verified.','Solve the Power of the Elements book\'s three elemental trials.','Fire Storm learned from the completed book','Blizzard and Lightning Storm purchases',[dest('skyrim','Windward Ruins','Windward Ruins'),dest('skyrim','North Skybound Watch','North Skybound Watch'),dest('skyrim','Four Skull Lookout','Four Skull Lookout')],'https://skyrim.fandom.com/wiki/Destruction_Ritual_Spell'),
 ('Alteration','Tolfdir','90 Alteration in the base-game reference.','Find Kahvozein\'s Fang and use it to recover Dragon Heartscales.','Dragonhide spell tome','Mass Paralysis purchases',[dest('skyrim','Assigned dagger dungeon / a dragon corpse')],'https://skyrim.fandom.com/wiki/Alteration_Ritual_Spell'),
 ('Restoration','Colette Marence','90 Restoration and completion of Good Intentions in the base-game reference.','Meet the Augur of Dunlain and survive his Restoration test.','Bane of the Undead learned from the Augur','Guardian Circle purchases',[dest('skyrim','The Midden Dark','College of Winterhold')],'https://skyrim.fandom.com/wiki/Restoration_Ritual_Spell')]
html=(P/'catalog-source.html').read_text();match=re.search(r'<script\b[^>]*\bid=["\']dataset["\'][^>]*>(.*?)</script>',html,re.S)
assert match,'Original embedded catalog missing';raw=json.loads(match.group(1));assert len(raw)==617
for school,who,gate,hook,free,shop,dsts,url in rituals:
 rows=[reward(free,'completion','Base-game quest reward; spell balance and presentation can differ in the installed magic stack.',**sp(school)),reward(shop,'unlock','Purchasing is unlocked; these are not all awarded free.',**sp(school))]
 if school=='Conjuration':rows.append(reward('Sigil Stone returned','completion','Retain the quest\'s returned stone for the Atronach Forge.',**book))
 for r in raw:
  if r['LO #']=='41' and 'Master' in r['When to look'] and school in r['When to look']:
   rows.append(w(r['Catalog ID'],'unlock','Purchase unlock only; see the linked item\'s skill and PS5 version notes.'))
 notes=['Base quest route and vanilla reward names are separated from Apocalypse\'s documented master-tome unlocks. The installed Mysticism / Odin / Apocalypse stack may alter individual spells or gates.']
 srcs=[source(url,school+' ritual: original quest route and rewards','Base-game reference, not certification of modded skill gates or spell statistics.'),source(N+'1090','Apocalypse: master-school ritual requirements','Original author gates; recorded v10.2.2 versus current author v10.3.0 remains a version qualification.')]
 if school=='Illusion':srcs.append(source(E+'Illusion_%28Skyrim%29','Illusion skill reference','Documents the standard 100-skill master quest; references differ on the 90/100 gate.'))
 if school=='Restoration':srcs.append(source('https://www.gamerguides.com/the-elder-scrolls-v-skyrim-anniversary-edition/guide/college-of-winterhold/college-of-winterhold-misc-quests/restoration-ritual-spell','Guardian Circle purchase unlock','Base-game walkthrough.'))
 add(school+' Ritual Spell',A,41,'Existing quest · magic unlock',start('skyrim','College of Winterhold','College of Winterhold',f'Ask {who} about further {school} training.','College of Winterhold','hub'),hook,rows,srcs,destinations=dsts,requirements=[req('School / quest gate',gate)],notes=notes)
add('The Cursed Tribe',ART,61,'Existing quest · modded loot',start('skyrim','The Rift / Largashbur','Atub at Largashbur','Help with the giant attack and speak to Atub.','Largashbur'),'Help an Orc stronghold seek Malacath\'s judgment.',[w('W372','completion','Take Volendrung from the shrine at the conclusion; it is not just a journal notification.'),reward('Surviving stronghold followers','unlock','Ogol, Ugor and Lob may become recruitable if they survive.',**book)],[source(E+'The_Cursed_Tribe','The Cursed Tribe: start, requirements and rewards','Base-game acquisition; Artificer\'s effect remains in W372.')],destinations=[dest('skyrim','Fallowstone Cave / Giant\'s Grove','Fallowstone Cave')],requirements=[req('Base-game level gate','Level 9.'),req('Bring','Troll Fat and a Daedra Heart for Atub\'s ritual.')])
add('Waking Nightmare',ART,61,'Existing quest · modded loot',start('skyrim','Dawnstar','Erandur at the Windpeak Inn','Speak to Erandur about the town\'s nightmares.','Dawnstar','hub'),'Investigate the dreams haunting Dawnstar.',[w('W370','choice','The artifact and follower outcomes are alternatives.'),reward('Erandur as a follower','choice','Available on the outcome that preserves him; not awarded alongside the staff by default.',**book)],[source(E+'Waking_Nightmare','Waking Nightmare: branch rewards','Base-game quest reference; modded staff effect remains in W370.')],destinations=[dest('skyrim','Nightcaller Temple','Nightcaller Temple')],spoilers='Let Erandur finish the ritual to preserve him as a potential follower, or kill him during it to claim the Skull of Corruption.')
add('A Night to Remember',ART,61,'Existing quest · modded loot',start('skyrim','Variable inn encounter','Sam Guevenne in an inn','At level 14 or above, look for Sam and accept his drinking contest. His inn is not fixed across playthroughs.'),'Piece together an ill-advised night out.',[w('W369','completion')],[source(E+'A_Night_to_Remember_%28Skyrim%29','A Night to Remember: starter and reward','Base-game route; Artificer\'s staff effect remains in W369.')],destinations=[dest('skyrim','The trail eventually reaches Morvunskar','Morvunskar')],requirements=[req('Base-game level gate','Level 14.')],notes=['No single tavern is pinned as a guaranteed Sam spawn.'])
add('The Taste of Death',ART,61,'Existing quest · modded loot',start('skyrim','Markarth','Brother Verulus / Hall of the Dead','Ask Verulus about the closed Hall of the Dead, then investigate and meet Eola.','Markarth','hub'),'Investigate a disturbing secret beneath Markarth.',[w('W368','choice','Conditional on following Namira\'s full reward route.'),reward('Eola as a follower','choice','Unlocked through the Namira route.',**book),reward('Gold for rescuing Verulus','choice','An alternative outcome; it fails the original Daedric quest and does not also grant the ring.',**book)],[source(E+'The_Taste_of_Death','The Taste of Death: reward branches','Base-game paths; no separate Namira-alternative mod is assumed.')],destinations=[dest('skyrim','Reachcliff Cave','Reachcliff Cave')],spoilers='Namira\'s ring requires sacrificing and feeding on Verulus. Rescuing him instead prevents that ring reward; it is not an exploit-based double-reward route.')
add('The Wolf Queen Awakened','Artificer / Knight of the North',159,'Existing quest · modded loot',start('skyrim','Solitude','Falk Firebeard in the Blue Palace','Follow Falk\'s courier summons after The Man Who Cried Wolf.','Solitude','hub'),'Return to the unresolved danger beneath Solitude.',[reward('Shield of Solitude','completion','The original completion shield; its current load-order enchantment is not expanded here.',category='Armor / clothing',armor='Light armor',slot='Shield'),reward('Leveled gold','completion','No fixed amount is promised.',**book),w('W363','unlock','Knight of the North clears ownership restrictions on the separately placed Sword of the Crusader in the Hall of the Dead. Collect it yourself.')],[source(E+'The_Wolf_Queen_Awakened','Wolf Queen: starter and rewards','Base-game quest reference.'),source('https://www.nexusmods.com/skyrimspecialedition/articles/3005','Knight of the North: sword ownership','Author-documented extra access, not an automatic sword award.')],destinations=[dest('skyrim','Solitude catacombs / Potema\'s Sanctum','Solitude')],requirements=[req('Required quest','The Man Who Cried Wolf; the base-game courier also depends on further level progression.')],chain=['Q032'])
add('Forbidden Legend','Skyrim / Artificer setup',61,'Existing quest · artifact hunt',start('skyrim','Multiple starting routes','Lost Legends book / a Gauldur clue','Read Lost Legends or discover a Gauldur fragment or writ; these provide leads into the legend.'),'Reunite three fragments of a lost amulet.',[reward('Gauldur Amulet','completion','Reforge and collect it at Reachwater Rock. Its final modded effect is not recorded in this quest card.',category='Jewelry',slot='Amulet / necklace'),reward('Gauldur Blackblade','boss','Loot from the Folgunthur route, not a final turn-in gift.',category='Weapons / ammunition',weapon='Sword',hand='One-handed'),reward('Gauldur Blackbow','boss','Loot from the Geirmund\'s Hall route, not a final turn-in gift.',category='Weapons / ammunition',weapon='Bow',hand='Ranged'),reward('Staff of Jyrik Gauldurson','optional','A Saarthal route pickup, not the final amulet reward.',category='Weapons / ammunition',weapon='Staff')],[source(E+'Forbidden_Legend','Forbidden Legend: routes and artifacts','Base-game acquisition; no unverified modded magnitudes are assigned.')],destinations=[dest('skyrim',n,n) for n in ['Folgunthur','Geirmund\'s Hall','Saarthal','Reachwater Rock']],requirements=[req('Access','The Saarthal portion requires College access through Under Saarthal.')])
add('The Black Star',ART,61,'Existing quest · modded loot',start('skyrim','Winterhold / Shrine of Azura','Aranea Ienith at the Shrine of Azura','Speak to Aranea to begin the search.','Shrine of Azura'),'Restore a Daedric artifact—or choose a different use for it.',[w('W366','choice','The Azura outcome; see its catalog entry for the qualified Artificer effect.'),reward('The Black Star','choice','Alternative reusable soul-gem artifact; its exact modded soul restrictions are not certified here.',**book),reward('Aranea as a follower','choice','Available through the Azura outcome, not the Nelacar outcome.',**book)],[source(E+'The_Black_Star_%28Quest%29','The Black Star: starter and choices','Base-game quest reference, with modded item scope preserved.')],destinations=[dest('skyrim','Ilinalta\'s Deep','Ilinalta\'s Deep'),dest('skyrim','Aranea or Nelacar in Winterhold','Winterhold')],spoilers='Return the broken star to Aranea for Azura\'s Star and her follower route; use Nelacar for the Black Star. These are alternative outcomes.')
add('Unearthed',ART,61,'Existing quest · modded loot',start('solstheim','Kolbjorn Barrow','Ralis Sedarys\'s excavation camp','Speak to Ralis outside Kolbjorn Barrow and fund the excavation.','Kolbjorn Barrow'),'Sponsor a dig that uncovers increasingly dangerous relics.',[reward('Ralis as a follower','choice','Recruitable if spared after the finale.',**book),w('W310','optional','Ahzidal\'s Ring of Necromancy is found during the excavation; it is not automatically awarded by Ralis.'),reward('Ahzidal armor relics','optional','Separate pickups during the excavation, not a turn-in set.',category='Armor / clothing',armor='Heavy armor',slot='Full set'),reward('Ahzidal\'s Ring of Arcana','optional','A separate excavation find; do not infer its final spell balance from the base-game name.',category='Jewelry',slot='Ring'),reward('Ahzidal mask','boss','Loot Ahzidal at the finale.',category='Armor / clothing',armor='Heavy armor',slot='Helmet / headwear'),reward('Black Book: Filament and Filigree','optional','The book opens its own Apocrypha power selection, separate from finishing Unearthed.',**book)],[source(E+'Unearthed_%28Dragonborn%29','Unearthed: relics, costs and outcome','Base-game acquisition; W310 retains Artificer\'s qualification.'),source('https://primagames.com/eguides/elder-scrolls-v-skyrim-eguide/quests/dragonborn-quests/solstheim-side-quests','Kolbjorn Black Book access','Official guide: Filament and Filigree, not The Sallow Regent.')],destinations=[dest('solstheim','Kolbjorn Barrow','Kolbjorn Barrow')],requirements=[req('Funding','The base-game excavation requires 11,000 gold across four payments and waiting for later stages.')],notes=['Optional exploration loot is separated from the outcome-dependent follower unlock.'])
add('Deathbrand','Artifact of Might - My Version',69,'Existing quest · modded loot',start('solstheim','Haknir\'s Shoal / book lead','Deathbrand book or the pirates at Haknir\'s Shoal','At level 36+, read Deathbrand or investigate the ancient chest and pirates at Haknir\'s Shoal.','Haknir’s Shoal'),'Hunt a pirate king\'s scattered armor and sealed treasure.',[reward('Soulrender','completion','Loot Haknir after the final fight; not an automatic inventory grant.',category='Weapons / ammunition',weapon='Sword',hand='One-handed'),reward('Bloodscythe','optional','Pick up the sword in the final chamber before the boss fight.',category='Weapons / ammunition',weapon='Sword',hand='One-handed'),reward('Deathbrand armor set','optional','Four separate ancient chests across Solstheim; collect them along the route.',category='Armor / clothing',armor='Light armor',slot='Full set'),w('W008','optional','Artifact of Might also places Raider\'s Axe in Gyldenhul Barrow; its original PS5 caveats remain.')],[source(E+'Deathbrand_%28Quest%29','Deathbrand: entry, armor hunt and swords','Base-game acquisition; W008 is separate mod-added loot.')],destinations=[dest('solstheim','Solstheim treasure chests'),dest('solstheim','Gyldenhul Barrow','Gyldenhul Barrow')],requirements=[req('Base-game level gate','Level 36.'),req('Bring','An Ancient Nordic Pickaxe for the stalhrim blocking access in Gyldenhul Barrow.')])
assert len(qs)==24
assert [q['id'] for q in qs]==[f'Q{i:03}' for i in range(23,47)]
print('Built 24 additional source-qualified quest cards, Q023–Q046.')
